// Generated by npm run build:site. Public documents only; never include account data.
export const STATIC_PAGES: Record<string, { html: string; markdown: string; tokens: number }> = {
  "/": {
    "html": "/__pages/8a5edab282632443.html",
    "markdown": "/__pages/8a5edab282632443.md",
    "tokens": 2917
  },
  "/examples": {
    "html": "/__pages/1a130cabaa8a47b0.html",
    "markdown": "/__pages/1a130cabaa8a47b0.md",
    "tokens": 34771
  },
  "/voices": {
    "html": "/__pages/3c1d9b7cb97eed20.html",
    "markdown": "/__pages/3c1d9b7cb97eed20.md",
    "tokens": 1015
  },
  "/companies": {
    "html": "/__pages/965e43e2b9e71740.html",
    "markdown": "/__pages/965e43e2b9e71740.md",
    "tokens": 1419
  },
  "/students": {
    "html": "/__pages/9a3f77bd97426a79.html",
    "markdown": "/__pages/9a3f77bd97426a79.md",
    "tokens": 896
  },
  "/mcp": {
    "html": "/__pages/88fe637beab867e2.html",
    "markdown": "/__pages/88fe637beab867e2.md",
    "tokens": 1641
  },
  "/rules": {
    "html": "/__pages/933053fc294245bb.html",
    "markdown": "/__pages/933053fc294245bb.md",
    "tokens": 1190
  },
  "/privacy": {
    "html": "/__pages/0ece7f7c306b4cf6.html",
    "markdown": "/__pages/0ece7f7c306b4cf6.md",
    "tokens": 2869
  },
  "/terms": {
    "html": "/__pages/2dda5c6b8eee51aa.html",
    "markdown": "/__pages/2dda5c6b8eee51aa.md",
    "tokens": 188
  },
  "/support": {
    "html": "/__pages/0b9f34c92865bdd1.html",
    "markdown": "/__pages/0b9f34c92865bdd1.md",
    "tokens": 274
  },
  "/blog": {
    "html": "/__pages/8caafe4386f95803.html",
    "markdown": "/__pages/8caafe4386f95803.md",
    "tokens": 1993
  },
  "/blog?page=2": {
    "html": "/__pages/0f0b1f7a021f2fa1.html",
    "markdown": "/__pages/0f0b1f7a021f2fa1.md",
    "tokens": 2030
  },
  "/blog?page=3": {
    "html": "/__pages/5d684d96eff29b6f.html",
    "markdown": "/__pages/5d684d96eff29b6f.md",
    "tokens": 1754
  },
  "/blog?page=4": {
    "html": "/__pages/c811387f89d4ec8d.html",
    "markdown": "/__pages/c811387f89d4ec8d.md",
    "tokens": 1700
  },
  "/blog?page=5": {
    "html": "/__pages/6250350dd420f994.html",
    "markdown": "/__pages/6250350dd420f994.md",
    "tokens": 1870
  },
  "/blog?page=6": {
    "html": "/__pages/8686aa3e95f6ad2e.html",
    "markdown": "/__pages/8686aa3e95f6ad2e.md",
    "tokens": 1829
  },
  "/blog?page=7": {
    "html": "/__pages/cee589bf74b1aae3.html",
    "markdown": "/__pages/cee589bf74b1aae3.md",
    "tokens": 2095
  },
  "/blog?page=8": {
    "html": "/__pages/4b966dd372686e87.html",
    "markdown": "/__pages/4b966dd372686e87.md",
    "tokens": 1974
  },
  "/blog?page=9": {
    "html": "/__pages/f52d36eef4f69053.html",
    "markdown": "/__pages/f52d36eef4f69053.md",
    "tokens": 876
  },
  "/blog/archive": {
    "html": "/__pages/555fc3431f69699a.html",
    "markdown": "/__pages/555fc3431f69699a.md",
    "tokens": 8564
  },
  "/blog/customer-story-flight-credit": {
    "html": "/__pages/4d462d33064c5ddf.html",
    "markdown": "/__pages/4d462d33064c5ddf.md",
    "tokens": 1273
  },
  "/blog/customer-story-rick-dinner-reservation": {
    "html": "/__pages/5023fc4d4837d0ba.html",
    "markdown": "/__pages/5023fc4d4837d0ba.md",
    "tokens": 1735
  },
  "/blog/customer-story-dental-appointments": {
    "html": "/__pages/aa1cb4c062716d89.html",
    "markdown": "/__pages/aa1cb4c062716d89.md",
    "tokens": 1658
  },
  "/blog/customer-story-joe-dress-shoes": {
    "html": "/__pages/29e60f3afffaf911.html",
    "markdown": "/__pages/29e60f3afffaf911.md",
    "tokens": 1516
  },
  "/blog/geico-customer-service": {
    "html": "/__pages/41d589203042a30a.html",
    "markdown": "/__pages/41d589203042a30a.md",
    "tokens": 6376
  },
  "/blog/doordash-customer-service-number": {
    "html": "/__pages/ff70cf03e5b76586.html",
    "markdown": "/__pages/ff70cf03e5b76586.md",
    "tokens": 4439
  },
  "/blog/priceline-customer-service": {
    "html": "/__pages/2a91c0a6d3a54c7c.html",
    "markdown": "/__pages/2a91c0a6d3a54c7c.md",
    "tokens": 5257
  },
  "/blog/venmo-customer-service-number": {
    "html": "/__pages/8ddc0d8e5d387de7.html",
    "markdown": "/__pages/8ddc0d8e5d387de7.md",
    "tokens": 8997
  },
  "/blog/everything-we-have-improved-since-launch": {
    "html": "/__pages/ee53e230a99841c0.html",
    "markdown": "/__pages/ee53e230a99841c0.md",
    "tokens": 2488
  },
  "/blog/delta-customer-service": {
    "html": "/__pages/61e1d8ba2e5289ea.html",
    "markdown": "/__pages/61e1d8ba2e5289ea.md",
    "tokens": 5142
  },
  "/blog/paypal-customer-service-number": {
    "html": "/__pages/14df76f086347bc7.html",
    "markdown": "/__pages/14df76f086347bc7.md",
    "tokens": 6019
  },
  "/blog/fifth-third-bank-customer-service": {
    "html": "/__pages/84b4a369f5053ffa.html",
    "markdown": "/__pages/84b4a369f5053ffa.md",
    "tokens": 4080
  },
  "/blog/aaa-insurance-customer-service": {
    "html": "/__pages/40f19e9468e5378f.html",
    "markdown": "/__pages/40f19e9468e5378f.md",
    "tokens": 4073
  },
  "/blog/directv-customer-service": {
    "html": "/__pages/3ae0ffa568610e73.html",
    "markdown": "/__pages/3ae0ffa568610e73.md",
    "tokens": 6843
  },
  "/blog/pottery-barn-customer-service": {
    "html": "/__pages/7d519b6ada502c05.html",
    "markdown": "/__pages/7d519b6ada502c05.md",
    "tokens": 3444
  },
  "/blog/hertz-customer-service-number": {
    "html": "/__pages/e3ebefa55d525ccc.html",
    "markdown": "/__pages/e3ebefa55d525ccc.md",
    "tokens": 9294
  },
  "/blog/hulu-customer-service-number": {
    "html": "/__pages/4f5cdd1adcfe8559.html",
    "markdown": "/__pages/4f5cdd1adcfe8559.md",
    "tokens": 3942
  },
  "/blog/windstream-customer-service": {
    "html": "/__pages/1b78d55294739307.html",
    "markdown": "/__pages/1b78d55294739307.md",
    "tokens": 7856
  },
  "/blog/how-long-to-reach-a-human": {
    "html": "/__pages/1624f2222bb89bf3.html",
    "markdown": "/__pages/1624f2222bb89bf3.md",
    "tokens": 6685
  },
  "/blog/vercel-ai-sdk-phone-calls": {
    "html": "/__pages/ff098db0a2035f3b.html",
    "markdown": "/__pages/ff098db0a2035f3b.md",
    "tokens": 2942
  },
  "/blog/vapi-alternatives": {
    "html": "/__pages/55c22a477aa2029e.html",
    "markdown": "/__pages/55c22a477aa2029e.md",
    "tokens": 3367
  },
  "/blog/bland-ai-alternatives": {
    "html": "/__pages/ae7d8f0f01361a52.html",
    "markdown": "/__pages/ae7d8f0f01361a52.md",
    "tokens": 3244
  },
  "/blog/ai-agent-that-makes-phone-calls": {
    "html": "/__pages/c6d4cf77fa9ecc89.html",
    "markdown": "/__pages/c6d4cf77fa9ecc89.md",
    "tokens": 2909
  },
  "/blog/gym-day-pass": {
    "html": "/__pages/58e8dd209383d03e.html",
    "markdown": "/__pages/58e8dd209383d03e.md",
    "tokens": 3601
  },
  "/blog/gyms-with-sauna-near-me": {
    "html": "/__pages/7629097141d8947d.html",
    "markdown": "/__pages/7629097141d8947d.md",
    "tokens": 2969
  },
  "/blog/how-much-does-blood-work-cost": {
    "html": "/__pages/a3d5d75459d562a5.html",
    "markdown": "/__pages/a3d5d75459d562a5.md",
    "tokens": 3072
  },
  "/blog/furniture-refinishing-cost": {
    "html": "/__pages/a940f850f4bf1e16.html",
    "markdown": "/__pages/a940f850f4bf1e16.md",
    "tokens": 2116
  },
  "/blog/couch-reupholstery-cost": {
    "html": "/__pages/cd4e7e91e42f43bd.html",
    "markdown": "/__pages/cd4e7e91e42f43bd.md",
    "tokens": 2125
  },
  "/blog/dog-teeth-cleaning-cost": {
    "html": "/__pages/381f0e4e9598e31b.html",
    "markdown": "/__pages/381f0e4e9598e31b.md",
    "tokens": 4356
  },
  "/blog/wheel-alignment-cost": {
    "html": "/__pages/5fff2e02afdd1065.html",
    "markdown": "/__pages/5fff2e02afdd1065.md",
    "tokens": 3085
  },
  "/blog/walmart-oil-change-prices": {
    "html": "/__pages/99fff13b3c5bdd6a.html",
    "markdown": "/__pages/99fff13b3c5bdd6a.md",
    "tokens": 2515
  },
  "/blog/how-to-cancel-siriusxm": {
    "html": "/__pages/89927a745702515f.html",
    "markdown": "/__pages/89927a745702515f.md",
    "tokens": 3058
  },
  "/blog/costco-eye-exam-cost": {
    "html": "/__pages/87eb50534995e24f.html",
    "markdown": "/__pages/87eb50534995e24f.md",
    "tokens": 4096
  },
  "/blog/cancel-crunch": {
    "html": "/__pages/70722b023a3a2b09.html",
    "markdown": "/__pages/70722b023a3a2b09.md",
    "tokens": 3921
  },
  "/blog/cancel-la-fitness": {
    "html": "/__pages/c3e0f3b4617bb976.html",
    "markdown": "/__pages/c3e0f3b4617bb976.md",
    "tokens": 4384
  },
  "/blog/ai-personal-assistant-appointment-booking": {
    "html": "/__pages/cb875b6b25b32048.html",
    "markdown": "/__pages/cb875b6b25b32048.md",
    "tokens": 3478
  },
  "/blog/macys-bow-tie-stock-check": {
    "html": "/__pages/a57fa317b216d261.html",
    "markdown": "/__pages/a57fa317b216d261.md",
    "tokens": 8620
  },
  "/blog/book-dinner-reservation-by-phone": {
    "html": "/__pages/91e553be51335771.html",
    "markdown": "/__pages/91e553be51335771.md",
    "tokens": 2854
  },
  "/blog/reschedule-doctor-appointment": {
    "html": "/__pages/58950964777a3366.html",
    "markdown": "/__pages/58950964777a3366.md",
    "tokens": 5168
  },
  "/blog/running-late-to-barber": {
    "html": "/__pages/3df0f1db1eb5aeb6.html",
    "markdown": "/__pages/3df0f1db1eb5aeb6.md",
    "tokens": 2201
  },
  "/blog/mandarin-phone-call-scheduling": {
    "html": "/__pages/573dcb48f1d75341.html",
    "markdown": "/__pages/573dcb48f1d75341.md",
    "tokens": 2627
  },
  "/blog/veterinary-behavior-consultation-call": {
    "html": "/__pages/041c2f0b9be1ffa4.html",
    "markdown": "/__pages/041c2f0b9be1ffa4.md",
    "tokens": 3838
  },
  "/blog/aquasana-return-exception": {
    "html": "/__pages/0cdf5c587fc9e991.html",
    "markdown": "/__pages/0cdf5c587fc9e991.md",
    "tokens": 5151
  },
  "/blog/running-late-to-appointment": {
    "html": "/__pages/46652be8ed2e540e.html",
    "markdown": "/__pages/46652be8ed2e540e.md",
    "tokens": 2755
  },
  "/blog/grok-bot-templates": {
    "html": "/__pages/f035c9b173e027ef.html",
    "markdown": "/__pages/f035c9b173e027ef.md",
    "tokens": 3567
  },
  "/blog/grok-bot-reusable-skills": {
    "html": "/__pages/aec25293ba23aad5.html",
    "markdown": "/__pages/aec25293ba23aad5.md",
    "tokens": 2524
  },
  "/blog/grok-bot-template-troubleshooting": {
    "html": "/__pages/53f7d63e40fb6e84.html",
    "markdown": "/__pages/53f7d63e40fb6e84.md",
    "tokens": 3006
  },
  "/blog/meta-muse-first-task": {
    "html": "/__pages/d49d86d498c31650.html",
    "markdown": "/__pages/d49d86d498c31650.md",
    "tokens": 5278
  },
  "/blog/muse-code-mcp-phone-calls": {
    "html": "/__pages/7400f73313c5b6b1.html",
    "markdown": "/__pages/7400f73313c5b6b1.md",
    "tokens": 3663
  },
  "/blog/grok-bot-vs-meta-muse": {
    "html": "/__pages/92e78061587d9843.html",
    "markdown": "/__pages/92e78061587d9843.md",
    "tokens": 2737
  },
  "/blog/meta-muse-supplier-quotes": {
    "html": "/__pages/c4ae492a3b9565cc.html",
    "markdown": "/__pages/c4ae492a3b9565cc.md",
    "tokens": 2286
  },
  "/blog/wyoming-registered-agent-consent-form": {
    "html": "/__pages/0bf23a868439d3a1.html",
    "markdown": "/__pages/0bf23a868439d3a1.md",
    "tokens": 4023
  },
  "/blog/ohio-workers-compensation-insurance": {
    "html": "/__pages/e79ce27a7744bfd3.html",
    "markdown": "/__pages/e79ce27a7744bfd3.md",
    "tokens": 4255
  },
  "/blog/drop-off-vet-appointment": {
    "html": "/__pages/19b297077f9d1c0a.html",
    "markdown": "/__pages/19b297077f9d1c0a.md",
    "tokens": 4376
  },
  "/blog/book-haircut-appointment": {
    "html": "/__pages/9eaed74ec63d7553.html",
    "markdown": "/__pages/9eaed74ec63d7553.md",
    "tokens": 3316
  },
  "/blog/les-schwab-oil-change": {
    "html": "/__pages/ba48431d0e7bdb1b.html",
    "markdown": "/__pages/ba48431d0e7bdb1b.md",
    "tokens": 4279
  },
  "/blog/t3-code-phone-calls": {
    "html": "/__pages/c4487b0143fe433f.html",
    "markdown": "/__pages/c4487b0143fe433f.md",
    "tokens": 4496
  },
  "/blog/schedule-phone-calls-claude-code-codex": {
    "html": "/__pages/ed6525f569adc849.html",
    "markdown": "/__pages/ed6525f569adc849.md",
    "tokens": 4739
  },
  "/blog/ai-phone-tree-navigation": {
    "html": "/__pages/2aec3a158421265c.html",
    "markdown": "/__pages/2aec3a158421265c.md",
    "tokens": 6024
  },
  "/blog/twilio-mcp-phone-calls": {
    "html": "/__pages/08398e894029722b.html",
    "markdown": "/__pages/08398e894029722b.md",
    "tokens": 4176
  },
  "/blog/instinct-ai-phone-calls": {
    "html": "/__pages/7d8b01a75a9d6b95.html",
    "markdown": "/__pages/7d8b01a75a9d6b95.md",
    "tokens": 4005
  },
  "/blog/claude-code-phone-calls": {
    "html": "/__pages/b4a4a35039232bdd.html",
    "markdown": "/__pages/b4a4a35039232bdd.md",
    "tokens": 5760
  },
  "/blog/codex-phone-calls": {
    "html": "/__pages/3348257799ac3891.html",
    "markdown": "/__pages/3348257799ac3891.md",
    "tokens": 3907
  },
  "/blog/agent-web-research-phone-calls-sf-private-dining": {
    "html": "/__pages/5d9174de815b6805.html",
    "markdown": "/__pages/5d9174de815b6805.md",
    "tokens": 8260
  },
  "/blog/phone-calling-mcp-comparison": {
    "html": "/__pages/59a59e92f1223e3d.html",
    "markdown": "/__pages/59a59e92f1223e3d.md",
    "tokens": 9601
  },
  "/blog/cascaded-voice-stack-vs-gpt-live": {
    "html": "/__pages/aeae359d4c5c3e33.html",
    "markdown": "/__pages/aeae359d4c5c3e33.md",
    "tokens": 5496
  },
  "/blog/cancel-factor": {
    "html": "/__pages/505eb83b629fa414.html",
    "markdown": "/__pages/505eb83b629fa414.md",
    "tokens": 7123
  },
  "/blog/cancel-fubo": {
    "html": "/__pages/3dc7b09613d1d44b.html",
    "markdown": "/__pages/3dc7b09613d1d44b.md",
    "tokens": 6234
  },
  "/blog/cancel-hellofresh": {
    "html": "/__pages/aaaf2401e7aa337b.html",
    "markdown": "/__pages/aaaf2401e7aa337b.md",
    "tokens": 4866
  },
  "/blog/allstate-customer-service-number": {
    "html": "/__pages/9ac645ac6d4e4820.html",
    "markdown": "/__pages/9ac645ac6d4e4820.md",
    "tokens": 4460
  },
  "/blog/cancel-audible": {
    "html": "/__pages/5aba5afde50e26d0.html",
    "markdown": "/__pages/5aba5afde50e26d0.md",
    "tokens": 4758
  },
  "/blog/fabletics-customer-service": {
    "html": "/__pages/5b5c1e7011303734.html",
    "markdown": "/__pages/5b5c1e7011303734.md",
    "tokens": 5556
  },
  "/blog/eye-exam-cost-without-insurance": {
    "html": "/__pages/759663bac5eb4427.html",
    "markdown": "/__pages/759663bac5eb4427.md",
    "tokens": 5846
  },
  "/blog/follow-up-appointment-telehealth": {
    "html": "/__pages/630731ffc3be9c50.html",
    "markdown": "/__pages/630731ffc3be9c50.md",
    "tokens": 3878
  },
  "/blog/private-dining-room-cost": {
    "html": "/__pages/071eeba541fc558a.html",
    "markdown": "/__pages/071eeba541fc558a.md",
    "tokens": 9144
  },
  "/blog/how-to-transfer-a-prescription": {
    "html": "/__pages/a4b0bfb79d180b15.html",
    "markdown": "/__pages/a4b0bfb79d180b15.md",
    "tokens": 7162
  },
  "/blog/amazon-pharmacy-phone-number": {
    "html": "/__pages/f7a8acf08130706e.html",
    "markdown": "/__pages/f7a8acf08130706e.md",
    "tokens": 4375
  },
  "/blog/grok-connectors-mcp-phone-calls": {
    "html": "/__pages/dd53a82fc808756f.html",
    "markdown": "/__pages/dd53a82fc808756f.md",
    "tokens": 5937
  },
  "/blog/meta-muse-ai-agent-phone-calls": {
    "html": "/__pages/6b5da232c9e22e22.html",
    "markdown": "/__pages/6b5da232c9e22e22.md",
    "tokens": 4553
  },
  "/blog/etihad-customer-service": {
    "html": "/__pages/a609f08f0c294628.html",
    "markdown": "/__pages/a609f08f0c294628.md",
    "tokens": 6854
  },
  "/blog/lawyer-consultation-fee": {
    "html": "/__pages/ee87b1a08149cfbd.html",
    "markdown": "/__pages/ee87b1a08149cfbd.md",
    "tokens": 5665
  },
  "/blog/american-airlines-flight-credit": {
    "html": "/__pages/54dd6bcdbea387c1.html",
    "markdown": "/__pages/54dd6bcdbea387c1.md",
    "tokens": 11021
  },
  "/blog/adderall-shortage": {
    "html": "/__pages/0fe25dd718aaf032.html",
    "markdown": "/__pages/0fe25dd718aaf032.md",
    "tokens": 9221
  },
  "/blog/how-to-find-a-new-primary-care-doctor": {
    "html": "/__pages/035614e93447d90b.html",
    "markdown": "/__pages/035614e93447d90b.md",
    "tokens": 22357
  },
  "/blog/usaa-phone-number": {
    "html": "/__pages/a70b41d595149573.html",
    "markdown": "/__pages/a70b41d595149573.md",
    "tokens": 4996
  },
  "/blog/ups-contact-number": {
    "html": "/__pages/e368946ff169194f.html",
    "markdown": "/__pages/e368946ff169194f.md",
    "tokens": 6321
  },
  "/blog/verizon-customer-service": {
    "html": "/__pages/6cfd54b00e65d985.html",
    "markdown": "/__pages/6cfd54b00e65d985.md",
    "tokens": 10980
  },
  "/blog/fpl-phone-number": {
    "html": "/__pages/f5806291e5d3e637.html",
    "markdown": "/__pages/f5806291e5d3e637.md",
    "tokens": 10092
  },
  "/blog/fedex-customer-service-number": {
    "html": "/__pages/d15a265e3315048f.html",
    "markdown": "/__pages/d15a265e3315048f.md",
    "tokens": 10873
  },
  "/blog/united-change-flight": {
    "html": "/__pages/a3ec4a65792b971c.html",
    "markdown": "/__pages/a3ec4a65792b971c.md",
    "tokens": 6169
  },
  "/blog/unitedhealthcare-phone-number": {
    "html": "/__pages/8f9029f0cf73d4f9.html",
    "markdown": "/__pages/8f9029f0cf73d4f9.md",
    "tokens": 5066
  },
  "/blog/need-dress-shoes-today": {
    "html": "/__pages/18c64c271fefb021.html",
    "markdown": "/__pages/18c64c271fefb021.md",
    "tokens": 7770
  },
  "/blog/spectrum-retention-department": {
    "html": "/__pages/cad6a590d97a2bfd.html",
    "markdown": "/__pages/cad6a590d97a2bfd.md",
    "tokens": 6437
  },
  "/blog/experian-phone-number": {
    "html": "/__pages/a1897270700e714d.html",
    "markdown": "/__pages/a1897270700e714d.md",
    "tokens": 4234
  },
  "/blog/cancel-planet-fitness": {
    "html": "/__pages/a9a59bfd1e8c3da5.html",
    "markdown": "/__pages/a9a59bfd1e8c3da5.md",
    "tokens": 3757
  },
  "/blog/wayfair-customer-service": {
    "html": "/__pages/3ce73872b4d7c2b7.html",
    "markdown": "/__pages/3ce73872b4d7c2b7.md",
    "tokens": 4248
  },
  "/blog/costco-tire-appointment-cancel-refund": {
    "html": "/__pages/ca5f5983d7127c65.html",
    "markdown": "/__pages/ca5f5983d7127c65.md",
    "tokens": 4397
  },
  "/blog/reschedule-dentist-appointment": {
    "html": "/__pages/1b1129e38f43b43f.html",
    "markdown": "/__pages/1b1129e38f43b43f.md",
    "tokens": 2667
  },
  "/blog/junk-removal-cost": {
    "html": "/__pages/3f44cdf8260b9b11.html",
    "markdown": "/__pages/3f44cdf8260b9b11.md",
    "tokens": 4361
  },
  "/blog/openai-realtime-voices-phone-calls": {
    "html": "/__pages/bfa7fe3d0cc5780a.html",
    "markdown": "/__pages/bfa7fe3d0cc5780a.md",
    "tokens": 9198
  }
};
