// Generated by npm run blog:related. Review matches before publishing.
export const RELATED_METADATA = {
  "model": "onnx-community/embeddinggemma-300m-ONNX",
  "revision": "5090578d9565bb06545b4552f76e6bc2c93e4a66",
  "dtype": "q8",
  "prompt": "task: sentence similarity | query: ",
  "recipe": "concise-title-specific-tags-shared-editorial-subject-v1",
  "minimumSimilarity": 0.6,
  "sourceHash": "a09157b1eb5fce53ce75fa17f3e32d774efae87f96a5efb7c3cda70a17ee09bb"
};

export const RELATED_INDEX: Record<string, { slug: string; similarity: number }[]> = {
  "aaa-insurance-customer-service": [
    {
      "slug": "allstate-customer-service-number",
      "similarity": 0.821309
    },
    {
      "slug": "unitedhealthcare-phone-number",
      "similarity": 0.743579
    },
    {
      "slug": "usaa-phone-number",
      "similarity": 0.70714
    },
    {
      "slug": "ohio-workers-compensation-insurance",
      "similarity": 0.616301
    }
  ],
  "adderall-shortage": [
    {
      "slug": "how-to-transfer-a-prescription",
      "similarity": 0.610341
    },
    {
      "slug": "amazon-pharmacy-phone-number",
      "similarity": 0.605305
    }
  ],
  "agent-web-research-phone-calls-sf-private-dining": [
    {
      "slug": "ai-agent-that-makes-phone-calls",
      "similarity": 0.745648
    },
    {
      "slug": "ai-personal-assistant-appointment-booking",
      "similarity": 0.744557
    },
    {
      "slug": "instinct-ai-phone-calls",
      "similarity": 0.715197
    },
    {
      "slug": "openai-realtime-voices-phone-calls",
      "similarity": 0.69509
    },
    {
      "slug": "book-dinner-reservation-by-phone",
      "similarity": 0.688874
    },
    {
      "slug": "bland-ai-alternatives",
      "similarity": 0.660738
    },
    {
      "slug": "vercel-ai-sdk-phone-calls",
      "similarity": 0.653575
    },
    {
      "slug": "claude-code-phone-calls",
      "similarity": 0.650623
    }
  ],
  "ai-agent-that-makes-phone-calls": [
    {
      "slug": "vercel-ai-sdk-phone-calls",
      "similarity": 0.802288
    },
    {
      "slug": "instinct-ai-phone-calls",
      "similarity": 0.798701
    },
    {
      "slug": "openai-realtime-voices-phone-calls",
      "similarity": 0.798544
    },
    {
      "slug": "agent-web-research-phone-calls-sf-private-dining",
      "similarity": 0.745648
    },
    {
      "slug": "claude-code-phone-calls",
      "similarity": 0.743339
    },
    {
      "slug": "cascaded-voice-stack-vs-gpt-live",
      "similarity": 0.728463
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.707018
    },
    {
      "slug": "bland-ai-alternatives",
      "similarity": 0.705434
    }
  ],
  "ai-personal-assistant-appointment-booking": [
    {
      "slug": "mandarin-phone-call-scheduling",
      "similarity": 0.749489
    },
    {
      "slug": "reschedule-doctor-appointment",
      "similarity": 0.745613
    },
    {
      "slug": "agent-web-research-phone-calls-sf-private-dining",
      "similarity": 0.744557
    },
    {
      "slug": "book-dinner-reservation-by-phone",
      "similarity": 0.694747
    },
    {
      "slug": "running-late-to-appointment",
      "similarity": 0.690496
    },
    {
      "slug": "follow-up-appointment-telehealth",
      "similarity": 0.670663
    }
  ],
  "ai-phone-tree-navigation": [
    {
      "slug": "twilio-mcp-phone-calls",
      "similarity": 0.801867
    },
    {
      "slug": "schedule-phone-calls-claude-code-codex",
      "similarity": 0.797743
    },
    {
      "slug": "phone-calling-mcp-comparison",
      "similarity": 0.777226
    },
    {
      "slug": "claude-code-phone-calls",
      "similarity": 0.741367
    },
    {
      "slug": "codex-phone-calls",
      "similarity": 0.738491
    },
    {
      "slug": "openai-realtime-voices-phone-calls",
      "similarity": 0.720596
    },
    {
      "slug": "t3-code-phone-calls",
      "similarity": 0.701629
    },
    {
      "slug": "vercel-ai-sdk-phone-calls",
      "similarity": 0.698151
    }
  ],
  "allstate-customer-service-number": [
    {
      "slug": "aaa-insurance-customer-service",
      "similarity": 0.821309
    },
    {
      "slug": "unitedhealthcare-phone-number",
      "similarity": 0.723907
    },
    {
      "slug": "usaa-phone-number",
      "similarity": 0.659304
    },
    {
      "slug": "ohio-workers-compensation-insurance",
      "similarity": 0.65767
    }
  ],
  "amazon-pharmacy-phone-number": [
    {
      "slug": "how-to-transfer-a-prescription",
      "similarity": 0.743932
    },
    {
      "slug": "adderall-shortage",
      "similarity": 0.605305
    }
  ],
  "american-airlines-flight-credit": [
    {
      "slug": "united-change-flight",
      "similarity": 0.656043
    },
    {
      "slug": "etihad-customer-service",
      "similarity": 0.640959
    }
  ],
  "aquasana-return-exception": [],
  "bland-ai-alternatives": [
    {
      "slug": "ai-agent-that-makes-phone-calls",
      "similarity": 0.705434
    },
    {
      "slug": "instinct-ai-phone-calls",
      "similarity": 0.682061
    },
    {
      "slug": "claude-code-phone-calls",
      "similarity": 0.674341
    },
    {
      "slug": "agent-web-research-phone-calls-sf-private-dining",
      "similarity": 0.660738
    },
    {
      "slug": "vapi-alternatives",
      "similarity": 0.659144
    },
    {
      "slug": "cascaded-voice-stack-vs-gpt-live",
      "similarity": 0.645466
    },
    {
      "slug": "vercel-ai-sdk-phone-calls",
      "similarity": 0.63265
    },
    {
      "slug": "openai-realtime-voices-phone-calls",
      "similarity": 0.620267
    }
  ],
  "book-dinner-reservation-by-phone": [
    {
      "slug": "ai-personal-assistant-appointment-booking",
      "similarity": 0.694747
    },
    {
      "slug": "agent-web-research-phone-calls-sf-private-dining",
      "similarity": 0.688874
    },
    {
      "slug": "private-dining-room-cost",
      "similarity": 0.65722
    }
  ],
  "book-haircut-appointment": [
    {
      "slug": "running-late-to-barber",
      "similarity": 0.787512
    }
  ],
  "cancel-audible": [
    {
      "slug": "how-to-cancel-siriusxm",
      "similarity": 0.72005
    },
    {
      "slug": "cancel-planet-fitness",
      "similarity": 0.677504
    },
    {
      "slug": "cancel-crunch",
      "similarity": 0.667022
    },
    {
      "slug": "cancel-factor",
      "similarity": 0.656854
    },
    {
      "slug": "directv-customer-service",
      "similarity": 0.643833
    },
    {
      "slug": "cancel-la-fitness",
      "similarity": 0.622397
    },
    {
      "slug": "cancel-fubo",
      "similarity": 0.614567
    },
    {
      "slug": "hulu-customer-service-number",
      "similarity": 0.611928
    }
  ],
  "cancel-crunch": [
    {
      "slug": "cancel-la-fitness",
      "similarity": 0.900761
    },
    {
      "slug": "how-to-cancel-siriusxm",
      "similarity": 0.800201
    },
    {
      "slug": "cancel-planet-fitness",
      "similarity": 0.790517
    },
    {
      "slug": "cancel-hellofresh",
      "similarity": 0.681279
    },
    {
      "slug": "cancel-audible",
      "similarity": 0.667022
    },
    {
      "slug": "directv-customer-service",
      "similarity": 0.652966
    },
    {
      "slug": "cancel-factor",
      "similarity": 0.652617
    },
    {
      "slug": "gyms-with-sauna-near-me",
      "similarity": 0.618997
    }
  ],
  "cancel-factor": [
    {
      "slug": "cancel-hellofresh",
      "similarity": 0.770875
    },
    {
      "slug": "directv-customer-service",
      "similarity": 0.669382
    },
    {
      "slug": "cancel-planet-fitness",
      "similarity": 0.665681
    },
    {
      "slug": "cancel-audible",
      "similarity": 0.656854
    },
    {
      "slug": "cancel-crunch",
      "similarity": 0.652617
    },
    {
      "slug": "how-to-cancel-siriusxm",
      "similarity": 0.648412
    }
  ],
  "cancel-fubo": [
    {
      "slug": "cancel-audible",
      "similarity": 0.614567
    },
    {
      "slug": "cancel-hellofresh",
      "similarity": 0.607155
    }
  ],
  "cancel-hellofresh": [
    {
      "slug": "cancel-factor",
      "similarity": 0.770875
    },
    {
      "slug": "cancel-crunch",
      "similarity": 0.681279
    },
    {
      "slug": "cancel-la-fitness",
      "similarity": 0.680435
    },
    {
      "slug": "directv-customer-service",
      "similarity": 0.648485
    },
    {
      "slug": "cancel-planet-fitness",
      "similarity": 0.640502
    },
    {
      "slug": "how-to-cancel-siriusxm",
      "similarity": 0.610796
    },
    {
      "slug": "cancel-fubo",
      "similarity": 0.607155
    }
  ],
  "cancel-la-fitness": [
    {
      "slug": "cancel-crunch",
      "similarity": 0.900761
    },
    {
      "slug": "cancel-planet-fitness",
      "similarity": 0.765293
    },
    {
      "slug": "how-to-cancel-siriusxm",
      "similarity": 0.748767
    },
    {
      "slug": "cancel-hellofresh",
      "similarity": 0.680435
    },
    {
      "slug": "gyms-with-sauna-near-me",
      "similarity": 0.62754
    },
    {
      "slug": "directv-customer-service",
      "similarity": 0.625885
    },
    {
      "slug": "cancel-audible",
      "similarity": 0.622397
    },
    {
      "slug": "gym-day-pass",
      "similarity": 0.605106
    }
  ],
  "cancel-planet-fitness": [
    {
      "slug": "cancel-crunch",
      "similarity": 0.790517
    },
    {
      "slug": "cancel-la-fitness",
      "similarity": 0.765293
    },
    {
      "slug": "directv-customer-service",
      "similarity": 0.681225
    },
    {
      "slug": "cancel-audible",
      "similarity": 0.677504
    },
    {
      "slug": "how-to-cancel-siriusxm",
      "similarity": 0.674339
    },
    {
      "slug": "cancel-factor",
      "similarity": 0.665681
    },
    {
      "slug": "cancel-hellofresh",
      "similarity": 0.640502
    }
  ],
  "cascaded-voice-stack-vs-gpt-live": [
    {
      "slug": "openai-realtime-voices-phone-calls",
      "similarity": 0.793055
    },
    {
      "slug": "ai-agent-that-makes-phone-calls",
      "similarity": 0.728463
    },
    {
      "slug": "phone-calling-mcp-comparison",
      "similarity": 0.71375
    },
    {
      "slug": "grok-bot-vs-meta-muse",
      "similarity": 0.707673
    },
    {
      "slug": "instinct-ai-phone-calls",
      "similarity": 0.70033
    },
    {
      "slug": "vercel-ai-sdk-phone-calls",
      "similarity": 0.695389
    },
    {
      "slug": "ai-phone-tree-navigation",
      "similarity": 0.680091
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.674866
    }
  ],
  "claude-code-phone-calls": [
    {
      "slug": "schedule-phone-calls-claude-code-codex",
      "similarity": 0.787107
    },
    {
      "slug": "twilio-mcp-phone-calls",
      "similarity": 0.753154
    },
    {
      "slug": "ai-agent-that-makes-phone-calls",
      "similarity": 0.743339
    },
    {
      "slug": "ai-phone-tree-navigation",
      "similarity": 0.741367
    },
    {
      "slug": "phone-calling-mcp-comparison",
      "similarity": 0.739932
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.73616
    },
    {
      "slug": "t3-code-phone-calls",
      "similarity": 0.72356
    },
    {
      "slug": "codex-phone-calls",
      "similarity": 0.71673
    }
  ],
  "codex-phone-calls": [
    {
      "slug": "t3-code-phone-calls",
      "similarity": 0.82945
    },
    {
      "slug": "phone-calling-mcp-comparison",
      "similarity": 0.772739
    },
    {
      "slug": "twilio-mcp-phone-calls",
      "similarity": 0.769399
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.75509
    },
    {
      "slug": "ai-phone-tree-navigation",
      "similarity": 0.738491
    },
    {
      "slug": "openai-realtime-voices-phone-calls",
      "similarity": 0.729409
    },
    {
      "slug": "schedule-phone-calls-claude-code-codex",
      "similarity": 0.719989
    },
    {
      "slug": "claude-code-phone-calls",
      "similarity": 0.71673
    }
  ],
  "costco-eye-exam-cost": [
    {
      "slug": "eye-exam-cost-without-insurance",
      "similarity": 0.709457
    },
    {
      "slug": "how-much-does-blood-work-cost",
      "similarity": 0.668936
    },
    {
      "slug": "running-late-to-appointment",
      "similarity": 0.60358
    }
  ],
  "costco-tire-appointment-cancel-refund": [],
  "couch-reupholstery-cost": [
    {
      "slug": "furniture-refinishing-cost",
      "similarity": 0.906678
    },
    {
      "slug": "junk-removal-cost",
      "similarity": 0.650278
    },
    {
      "slug": "pottery-barn-customer-service",
      "similarity": 0.616362
    }
  ],
  "delta-customer-service": [
    {
      "slug": "etihad-customer-service",
      "similarity": 0.736721
    },
    {
      "slug": "how-long-to-reach-a-human",
      "similarity": 0.621233
    }
  ],
  "directv-customer-service": [
    {
      "slug": "verizon-customer-service",
      "similarity": 0.72871
    },
    {
      "slug": "how-to-cancel-siriusxm",
      "similarity": 0.714801
    },
    {
      "slug": "hulu-customer-service-number",
      "similarity": 0.7114
    },
    {
      "slug": "cancel-planet-fitness",
      "similarity": 0.681225
    },
    {
      "slug": "cancel-factor",
      "similarity": 0.669382
    },
    {
      "slug": "windstream-customer-service",
      "similarity": 0.656042
    },
    {
      "slug": "cancel-crunch",
      "similarity": 0.652966
    },
    {
      "slug": "cancel-hellofresh",
      "similarity": 0.648485
    }
  ],
  "dog-teeth-cleaning-cost": [
    {
      "slug": "veterinary-behavior-consultation-call",
      "similarity": 0.704433
    },
    {
      "slug": "drop-off-vet-appointment",
      "similarity": 0.629749
    }
  ],
  "drop-off-vet-appointment": [
    {
      "slug": "veterinary-behavior-consultation-call",
      "similarity": 0.725356
    },
    {
      "slug": "dog-teeth-cleaning-cost",
      "similarity": 0.629749
    }
  ],
  "etihad-customer-service": [
    {
      "slug": "delta-customer-service",
      "similarity": 0.736721
    },
    {
      "slug": "american-airlines-flight-credit",
      "similarity": 0.640959
    },
    {
      "slug": "united-change-flight",
      "similarity": 0.622989
    }
  ],
  "everything-we-have-improved-since-launch": [
    {
      "slug": "vercel-ai-sdk-phone-calls",
      "similarity": 0.634782
    },
    {
      "slug": "meta-muse-first-task",
      "similarity": 0.620394
    }
  ],
  "experian-phone-number": [
    {
      "slug": "usaa-phone-number",
      "similarity": 0.612386
    },
    {
      "slug": "paypal-customer-service-number",
      "similarity": 0.607467
    }
  ],
  "eye-exam-cost-without-insurance": [
    {
      "slug": "how-much-does-blood-work-cost",
      "similarity": 0.736028
    },
    {
      "slug": "costco-eye-exam-cost",
      "similarity": 0.709457
    }
  ],
  "fabletics-customer-service": [
    {
      "slug": "wayfair-customer-service",
      "similarity": 0.685328
    },
    {
      "slug": "pottery-barn-customer-service",
      "similarity": 0.678181
    },
    {
      "slug": "hulu-customer-service-number",
      "similarity": 0.643376
    },
    {
      "slug": "spectrum-retention-department",
      "similarity": 0.626885
    },
    {
      "slug": "directv-customer-service",
      "similarity": 0.606411
    }
  ],
  "fedex-customer-service-number": [
    {
      "slug": "ups-contact-number",
      "similarity": 0.851012
    }
  ],
  "fifth-third-bank-customer-service": [
    {
      "slug": "paypal-customer-service-number",
      "similarity": 0.693997
    },
    {
      "slug": "usaa-phone-number",
      "similarity": 0.659371
    }
  ],
  "follow-up-appointment-telehealth": [
    {
      "slug": "reschedule-doctor-appointment",
      "similarity": 0.784507
    },
    {
      "slug": "ai-personal-assistant-appointment-booking",
      "similarity": 0.670663
    },
    {
      "slug": "reschedule-dentist-appointment",
      "similarity": 0.659237
    },
    {
      "slug": "how-to-find-a-new-primary-care-doctor",
      "similarity": 0.628693
    },
    {
      "slug": "running-late-to-appointment",
      "similarity": 0.624917
    }
  ],
  "fpl-phone-number": [],
  "furniture-refinishing-cost": [
    {
      "slug": "couch-reupholstery-cost",
      "similarity": 0.906678
    },
    {
      "slug": "junk-removal-cost",
      "similarity": 0.673814
    },
    {
      "slug": "pottery-barn-customer-service",
      "similarity": 0.630691
    }
  ],
  "grok-bot-reusable-skills": [
    {
      "slug": "grok-bot-template-troubleshooting",
      "similarity": 0.841983
    },
    {
      "slug": "grok-bot-templates",
      "similarity": 0.774309
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.773681
    },
    {
      "slug": "grok-bot-vs-meta-muse",
      "similarity": 0.765883
    },
    {
      "slug": "ai-agent-that-makes-phone-calls",
      "similarity": 0.676581
    },
    {
      "slug": "vercel-ai-sdk-phone-calls",
      "similarity": 0.661641
    },
    {
      "slug": "instinct-ai-phone-calls",
      "similarity": 0.647303
    },
    {
      "slug": "cascaded-voice-stack-vs-gpt-live",
      "similarity": 0.642589
    }
  ],
  "grok-bot-template-troubleshooting": [
    {
      "slug": "grok-bot-reusable-skills",
      "similarity": 0.841983
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.798916
    },
    {
      "slug": "grok-bot-templates",
      "similarity": 0.763294
    },
    {
      "slug": "grok-bot-vs-meta-muse",
      "similarity": 0.740644
    },
    {
      "slug": "claude-code-phone-calls",
      "similarity": 0.693552
    },
    {
      "slug": "ai-agent-that-makes-phone-calls",
      "similarity": 0.680906
    },
    {
      "slug": "schedule-phone-calls-claude-code-codex",
      "similarity": 0.650104
    },
    {
      "slug": "instinct-ai-phone-calls",
      "similarity": 0.644672
    }
  ],
  "grok-bot-templates": [
    {
      "slug": "grok-bot-reusable-skills",
      "similarity": 0.774309
    },
    {
      "slug": "grok-bot-template-troubleshooting",
      "similarity": 0.763294
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.753859
    },
    {
      "slug": "grok-bot-vs-meta-muse",
      "similarity": 0.736964
    },
    {
      "slug": "ai-agent-that-makes-phone-calls",
      "similarity": 0.661093
    },
    {
      "slug": "instinct-ai-phone-calls",
      "similarity": 0.659982
    },
    {
      "slug": "vercel-ai-sdk-phone-calls",
      "similarity": 0.637192
    },
    {
      "slug": "meta-muse-first-task",
      "similarity": 0.634193
    }
  ],
  "grok-bot-vs-meta-muse": [
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.817182
    },
    {
      "slug": "grok-bot-reusable-skills",
      "similarity": 0.765883
    },
    {
      "slug": "grok-bot-template-troubleshooting",
      "similarity": 0.740644
    },
    {
      "slug": "grok-bot-templates",
      "similarity": 0.736964
    },
    {
      "slug": "meta-muse-first-task",
      "similarity": 0.733066
    },
    {
      "slug": "meta-muse-ai-agent-phone-calls",
      "similarity": 0.71639
    },
    {
      "slug": "cascaded-voice-stack-vs-gpt-live",
      "similarity": 0.707673
    },
    {
      "slug": "muse-code-mcp-phone-calls",
      "similarity": 0.700503
    }
  ],
  "grok-connectors-mcp-phone-calls": [
    {
      "slug": "grok-bot-vs-meta-muse",
      "similarity": 0.817182
    },
    {
      "slug": "grok-bot-template-troubleshooting",
      "similarity": 0.798916
    },
    {
      "slug": "grok-bot-reusable-skills",
      "similarity": 0.773681
    },
    {
      "slug": "t3-code-phone-calls",
      "similarity": 0.762346
    },
    {
      "slug": "twilio-mcp-phone-calls",
      "similarity": 0.758904
    },
    {
      "slug": "codex-phone-calls",
      "similarity": 0.75509
    },
    {
      "slug": "grok-bot-templates",
      "similarity": 0.753859
    },
    {
      "slug": "muse-code-mcp-phone-calls",
      "similarity": 0.749795
    }
  ],
  "gym-day-pass": [
    {
      "slug": "gyms-with-sauna-near-me",
      "similarity": 0.752682
    },
    {
      "slug": "cancel-crunch",
      "similarity": 0.61053
    },
    {
      "slug": "cancel-la-fitness",
      "similarity": 0.605106
    }
  ],
  "gyms-with-sauna-near-me": [
    {
      "slug": "gym-day-pass",
      "similarity": 0.752682
    },
    {
      "slug": "cancel-la-fitness",
      "similarity": 0.62754
    },
    {
      "slug": "cancel-crunch",
      "similarity": 0.618997
    }
  ],
  "hertz-customer-service-number": [],
  "how-long-to-reach-a-human": [
    {
      "slug": "delta-customer-service",
      "similarity": 0.621233
    },
    {
      "slug": "verizon-customer-service",
      "similarity": 0.607962
    }
  ],
  "how-much-does-blood-work-cost": [
    {
      "slug": "eye-exam-cost-without-insurance",
      "similarity": 0.736028
    },
    {
      "slug": "costco-eye-exam-cost",
      "similarity": 0.668936
    }
  ],
  "how-to-cancel-siriusxm": [
    {
      "slug": "cancel-crunch",
      "similarity": 0.800201
    },
    {
      "slug": "cancel-la-fitness",
      "similarity": 0.748767
    },
    {
      "slug": "cancel-audible",
      "similarity": 0.72005
    },
    {
      "slug": "directv-customer-service",
      "similarity": 0.714801
    },
    {
      "slug": "cancel-planet-fitness",
      "similarity": 0.674339
    },
    {
      "slug": "cancel-factor",
      "similarity": 0.648412
    },
    {
      "slug": "cancel-hellofresh",
      "similarity": 0.610796
    }
  ],
  "how-to-find-a-new-primary-care-doctor": [
    {
      "slug": "unitedhealthcare-phone-number",
      "similarity": 0.639327
    },
    {
      "slug": "follow-up-appointment-telehealth",
      "similarity": 0.628693
    },
    {
      "slug": "reschedule-doctor-appointment",
      "similarity": 0.614724
    }
  ],
  "how-to-transfer-a-prescription": [
    {
      "slug": "amazon-pharmacy-phone-number",
      "similarity": 0.743932
    },
    {
      "slug": "adderall-shortage",
      "similarity": 0.610341
    }
  ],
  "hulu-customer-service-number": [
    {
      "slug": "directv-customer-service",
      "similarity": 0.7114
    },
    {
      "slug": "fabletics-customer-service",
      "similarity": 0.643376
    },
    {
      "slug": "cancel-audible",
      "similarity": 0.611928
    }
  ],
  "instinct-ai-phone-calls": [
    {
      "slug": "ai-agent-that-makes-phone-calls",
      "similarity": 0.798701
    },
    {
      "slug": "vercel-ai-sdk-phone-calls",
      "similarity": 0.750655
    },
    {
      "slug": "agent-web-research-phone-calls-sf-private-dining",
      "similarity": 0.715197
    },
    {
      "slug": "meta-muse-ai-agent-phone-calls",
      "similarity": 0.709263
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.708639
    },
    {
      "slug": "openai-realtime-voices-phone-calls",
      "similarity": 0.704765
    },
    {
      "slug": "cascaded-voice-stack-vs-gpt-live",
      "similarity": 0.70033
    },
    {
      "slug": "twilio-mcp-phone-calls",
      "similarity": 0.694327
    }
  ],
  "junk-removal-cost": [
    {
      "slug": "furniture-refinishing-cost",
      "similarity": 0.673814
    },
    {
      "slug": "couch-reupholstery-cost",
      "similarity": 0.650278
    }
  ],
  "lawyer-consultation-fee": [],
  "les-schwab-oil-change": [
    {
      "slug": "wheel-alignment-cost",
      "similarity": 0.766277
    },
    {
      "slug": "walmart-oil-change-prices",
      "similarity": 0.749782
    }
  ],
  "macys-bow-tie-stock-check": [
    {
      "slug": "need-dress-shoes-today",
      "similarity": 0.640336
    },
    {
      "slug": "pottery-barn-customer-service",
      "similarity": 0.630702
    }
  ],
  "mandarin-phone-call-scheduling": [
    {
      "slug": "ai-personal-assistant-appointment-booking",
      "similarity": 0.749489
    }
  ],
  "meta-muse-ai-agent-phone-calls": [
    {
      "slug": "muse-code-mcp-phone-calls",
      "similarity": 0.930857
    },
    {
      "slug": "meta-muse-first-task",
      "similarity": 0.82718
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.736013
    },
    {
      "slug": "twilio-mcp-phone-calls",
      "similarity": 0.721087
    },
    {
      "slug": "grok-bot-vs-meta-muse",
      "similarity": 0.71639
    },
    {
      "slug": "instinct-ai-phone-calls",
      "similarity": 0.709263
    },
    {
      "slug": "phone-calling-mcp-comparison",
      "similarity": 0.70111
    },
    {
      "slug": "t3-code-phone-calls",
      "similarity": 0.693225
    }
  ],
  "meta-muse-first-task": [
    {
      "slug": "meta-muse-ai-agent-phone-calls",
      "similarity": 0.82718
    },
    {
      "slug": "muse-code-mcp-phone-calls",
      "similarity": 0.803269
    },
    {
      "slug": "grok-bot-vs-meta-muse",
      "similarity": 0.733066
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.663029
    },
    {
      "slug": "ai-agent-that-makes-phone-calls",
      "similarity": 0.658736
    },
    {
      "slug": "meta-muse-supplier-quotes",
      "similarity": 0.647238
    },
    {
      "slug": "openai-realtime-voices-phone-calls",
      "similarity": 0.644284
    },
    {
      "slug": "vercel-ai-sdk-phone-calls",
      "similarity": 0.642454
    }
  ],
  "meta-muse-supplier-quotes": [
    {
      "slug": "meta-muse-ai-agent-phone-calls",
      "similarity": 0.668127
    },
    {
      "slug": "meta-muse-first-task",
      "similarity": 0.647238
    },
    {
      "slug": "grok-bot-vs-meta-muse",
      "similarity": 0.636163
    },
    {
      "slug": "muse-code-mcp-phone-calls",
      "similarity": 0.630604
    }
  ],
  "muse-code-mcp-phone-calls": [
    {
      "slug": "meta-muse-ai-agent-phone-calls",
      "similarity": 0.930857
    },
    {
      "slug": "meta-muse-first-task",
      "similarity": 0.803269
    },
    {
      "slug": "twilio-mcp-phone-calls",
      "similarity": 0.762281
    },
    {
      "slug": "phone-calling-mcp-comparison",
      "similarity": 0.75772
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.749795
    },
    {
      "slug": "t3-code-phone-calls",
      "similarity": 0.748959
    },
    {
      "slug": "codex-phone-calls",
      "similarity": 0.704102
    },
    {
      "slug": "grok-bot-vs-meta-muse",
      "similarity": 0.700503
    }
  ],
  "need-dress-shoes-today": [
    {
      "slug": "macys-bow-tie-stock-check",
      "similarity": 0.640336
    }
  ],
  "ohio-workers-compensation-insurance": [
    {
      "slug": "allstate-customer-service-number",
      "similarity": 0.65767
    },
    {
      "slug": "unitedhealthcare-phone-number",
      "similarity": 0.616727
    },
    {
      "slug": "aaa-insurance-customer-service",
      "similarity": 0.616301
    }
  ],
  "openai-realtime-voices-phone-calls": [
    {
      "slug": "ai-agent-that-makes-phone-calls",
      "similarity": 0.798544
    },
    {
      "slug": "cascaded-voice-stack-vs-gpt-live",
      "similarity": 0.793055
    },
    {
      "slug": "codex-phone-calls",
      "similarity": 0.729409
    },
    {
      "slug": "ai-phone-tree-navigation",
      "similarity": 0.720596
    },
    {
      "slug": "vercel-ai-sdk-phone-calls",
      "similarity": 0.711173
    },
    {
      "slug": "instinct-ai-phone-calls",
      "similarity": 0.704765
    },
    {
      "slug": "agent-web-research-phone-calls-sf-private-dining",
      "similarity": 0.69509
    },
    {
      "slug": "claude-code-phone-calls",
      "similarity": 0.680441
    }
  ],
  "paypal-customer-service-number": [
    {
      "slug": "fifth-third-bank-customer-service",
      "similarity": 0.693997
    },
    {
      "slug": "usaa-phone-number",
      "similarity": 0.641118
    },
    {
      "slug": "experian-phone-number",
      "similarity": 0.607467
    }
  ],
  "phone-calling-mcp-comparison": [
    {
      "slug": "twilio-mcp-phone-calls",
      "similarity": 0.8697
    },
    {
      "slug": "schedule-phone-calls-claude-code-codex",
      "similarity": 0.782902
    },
    {
      "slug": "ai-phone-tree-navigation",
      "similarity": 0.777226
    },
    {
      "slug": "codex-phone-calls",
      "similarity": 0.772739
    },
    {
      "slug": "t3-code-phone-calls",
      "similarity": 0.767655
    },
    {
      "slug": "muse-code-mcp-phone-calls",
      "similarity": 0.75772
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.740261
    },
    {
      "slug": "claude-code-phone-calls",
      "similarity": 0.739932
    }
  ],
  "pottery-barn-customer-service": [
    {
      "slug": "wayfair-customer-service",
      "similarity": 0.805305
    },
    {
      "slug": "fabletics-customer-service",
      "similarity": 0.678181
    },
    {
      "slug": "macys-bow-tie-stock-check",
      "similarity": 0.630702
    },
    {
      "slug": "furniture-refinishing-cost",
      "similarity": 0.630691
    },
    {
      "slug": "couch-reupholstery-cost",
      "similarity": 0.616362
    }
  ],
  "private-dining-room-cost": [
    {
      "slug": "book-dinner-reservation-by-phone",
      "similarity": 0.65722
    },
    {
      "slug": "agent-web-research-phone-calls-sf-private-dining",
      "similarity": 0.639106
    }
  ],
  "reschedule-dentist-appointment": [
    {
      "slug": "reschedule-doctor-appointment",
      "similarity": 0.718744
    },
    {
      "slug": "follow-up-appointment-telehealth",
      "similarity": 0.659237
    }
  ],
  "reschedule-doctor-appointment": [
    {
      "slug": "follow-up-appointment-telehealth",
      "similarity": 0.784507
    },
    {
      "slug": "ai-personal-assistant-appointment-booking",
      "similarity": 0.745613
    },
    {
      "slug": "reschedule-dentist-appointment",
      "similarity": 0.718744
    },
    {
      "slug": "running-late-to-appointment",
      "similarity": 0.708862
    },
    {
      "slug": "how-to-find-a-new-primary-care-doctor",
      "similarity": 0.614724
    }
  ],
  "running-late-to-appointment": [
    {
      "slug": "reschedule-doctor-appointment",
      "similarity": 0.708862
    },
    {
      "slug": "ai-personal-assistant-appointment-booking",
      "similarity": 0.690496
    },
    {
      "slug": "follow-up-appointment-telehealth",
      "similarity": 0.624917
    },
    {
      "slug": "costco-eye-exam-cost",
      "similarity": 0.60358
    }
  ],
  "running-late-to-barber": [
    {
      "slug": "book-haircut-appointment",
      "similarity": 0.787512
    }
  ],
  "schedule-phone-calls-claude-code-codex": [
    {
      "slug": "twilio-mcp-phone-calls",
      "similarity": 0.806645
    },
    {
      "slug": "ai-phone-tree-navigation",
      "similarity": 0.797743
    },
    {
      "slug": "claude-code-phone-calls",
      "similarity": 0.787107
    },
    {
      "slug": "phone-calling-mcp-comparison",
      "similarity": 0.782902
    },
    {
      "slug": "codex-phone-calls",
      "similarity": 0.719989
    },
    {
      "slug": "t3-code-phone-calls",
      "similarity": 0.713228
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.705036
    },
    {
      "slug": "ai-agent-that-makes-phone-calls",
      "similarity": 0.702685
    }
  ],
  "spectrum-retention-department": [
    {
      "slug": "fabletics-customer-service",
      "similarity": 0.626885
    },
    {
      "slug": "directv-customer-service",
      "similarity": 0.61774
    }
  ],
  "t3-code-phone-calls": [
    {
      "slug": "codex-phone-calls",
      "similarity": 0.82945
    },
    {
      "slug": "twilio-mcp-phone-calls",
      "similarity": 0.785476
    },
    {
      "slug": "phone-calling-mcp-comparison",
      "similarity": 0.767655
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.762346
    },
    {
      "slug": "muse-code-mcp-phone-calls",
      "similarity": 0.748959
    },
    {
      "slug": "claude-code-phone-calls",
      "similarity": 0.72356
    },
    {
      "slug": "schedule-phone-calls-claude-code-codex",
      "similarity": 0.713228
    },
    {
      "slug": "ai-phone-tree-navigation",
      "similarity": 0.701629
    }
  ],
  "twilio-mcp-phone-calls": [
    {
      "slug": "phone-calling-mcp-comparison",
      "similarity": 0.8697
    },
    {
      "slug": "schedule-phone-calls-claude-code-codex",
      "similarity": 0.806645
    },
    {
      "slug": "ai-phone-tree-navigation",
      "similarity": 0.801867
    },
    {
      "slug": "t3-code-phone-calls",
      "similarity": 0.785476
    },
    {
      "slug": "codex-phone-calls",
      "similarity": 0.769399
    },
    {
      "slug": "muse-code-mcp-phone-calls",
      "similarity": 0.762281
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.758904
    },
    {
      "slug": "claude-code-phone-calls",
      "similarity": 0.753154
    }
  ],
  "united-change-flight": [
    {
      "slug": "american-airlines-flight-credit",
      "similarity": 0.656043
    },
    {
      "slug": "etihad-customer-service",
      "similarity": 0.622989
    }
  ],
  "unitedhealthcare-phone-number": [
    {
      "slug": "usaa-phone-number",
      "similarity": 0.76885
    },
    {
      "slug": "aaa-insurance-customer-service",
      "similarity": 0.743579
    },
    {
      "slug": "allstate-customer-service-number",
      "similarity": 0.723907
    },
    {
      "slug": "how-to-find-a-new-primary-care-doctor",
      "similarity": 0.639327
    },
    {
      "slug": "ohio-workers-compensation-insurance",
      "similarity": 0.616727
    }
  ],
  "ups-contact-number": [
    {
      "slug": "fedex-customer-service-number",
      "similarity": 0.851012
    }
  ],
  "usaa-phone-number": [
    {
      "slug": "unitedhealthcare-phone-number",
      "similarity": 0.76885
    },
    {
      "slug": "aaa-insurance-customer-service",
      "similarity": 0.70714
    },
    {
      "slug": "fifth-third-bank-customer-service",
      "similarity": 0.659371
    },
    {
      "slug": "allstate-customer-service-number",
      "similarity": 0.659304
    },
    {
      "slug": "paypal-customer-service-number",
      "similarity": 0.641118
    },
    {
      "slug": "experian-phone-number",
      "similarity": 0.612386
    }
  ],
  "vapi-alternatives": [
    {
      "slug": "ai-phone-tree-navigation",
      "similarity": 0.675324
    },
    {
      "slug": "twilio-mcp-phone-calls",
      "similarity": 0.663938
    },
    {
      "slug": "phone-calling-mcp-comparison",
      "similarity": 0.661788
    },
    {
      "slug": "bland-ai-alternatives",
      "similarity": 0.659144
    },
    {
      "slug": "schedule-phone-calls-claude-code-codex",
      "similarity": 0.624342
    }
  ],
  "vercel-ai-sdk-phone-calls": [
    {
      "slug": "ai-agent-that-makes-phone-calls",
      "similarity": 0.802288
    },
    {
      "slug": "instinct-ai-phone-calls",
      "similarity": 0.750655
    },
    {
      "slug": "openai-realtime-voices-phone-calls",
      "similarity": 0.711173
    },
    {
      "slug": "ai-phone-tree-navigation",
      "similarity": 0.698151
    },
    {
      "slug": "cascaded-voice-stack-vs-gpt-live",
      "similarity": 0.695389
    },
    {
      "slug": "muse-code-mcp-phone-calls",
      "similarity": 0.693975
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.685915
    },
    {
      "slug": "twilio-mcp-phone-calls",
      "similarity": 0.675152
    }
  ],
  "verizon-customer-service": [
    {
      "slug": "directv-customer-service",
      "similarity": 0.72871
    },
    {
      "slug": "windstream-customer-service",
      "similarity": 0.64429
    },
    {
      "slug": "how-long-to-reach-a-human",
      "similarity": 0.607962
    }
  ],
  "veterinary-behavior-consultation-call": [
    {
      "slug": "drop-off-vet-appointment",
      "similarity": 0.725356
    },
    {
      "slug": "dog-teeth-cleaning-cost",
      "similarity": 0.704433
    }
  ],
  "walmart-oil-change-prices": [
    {
      "slug": "wheel-alignment-cost",
      "similarity": 0.822895
    },
    {
      "slug": "les-schwab-oil-change",
      "similarity": 0.749782
    }
  ],
  "wayfair-customer-service": [
    {
      "slug": "pottery-barn-customer-service",
      "similarity": 0.805305
    },
    {
      "slug": "fabletics-customer-service",
      "similarity": 0.685328
    }
  ],
  "wheel-alignment-cost": [
    {
      "slug": "walmart-oil-change-prices",
      "similarity": 0.822895
    },
    {
      "slug": "les-schwab-oil-change",
      "similarity": 0.766277
    }
  ],
  "windstream-customer-service": [
    {
      "slug": "directv-customer-service",
      "similarity": 0.656042
    },
    {
      "slug": "verizon-customer-service",
      "similarity": 0.64429
    }
  ],
  "wyoming-registered-agent-consent-form": []
};
