// Generated by npm run blog:related. Review matches before publishing.
export const RELATED_METADATA = {
  "model": "onnx-community/embeddinggemma-300m-ONNX",
  "revision": "5090578d9565bb06545b4552f76e6bc2c93e4a66",
  "dtype": "q8",
  "prompt": "task: sentence similarity | query: ",
  "recipe": "concise-title-specific-tags-shared-editorial-subject-v1",
  "minimumSimilarity": 0.6,
  "sourceHash": "3f50286271c02514e45065ba698f30baaaecd5e559ba973dedba966b05feef57"
};

export const RELATED_INDEX: Record<string, { slug: string; similarity: number }[]> = {
  "aaa-insurance-customer-service": [
    {
      "slug": "allstate-customer-service-number",
      "similarity": 0.699861
    },
    {
      "slug": "geico-customer-service",
      "similarity": 0.669445
    },
    {
      "slug": "usaa-phone-number",
      "similarity": 0.652481
    },
    {
      "slug": "unitedhealthcare-phone-number",
      "similarity": 0.616224
    }
  ],
  "adderall-shortage": [
    {
      "slug": "how-to-transfer-a-prescription",
      "similarity": 0.610341
    }
  ],
  "agent-web-research-phone-calls-sf-private-dining": [
    {
      "slug": "ai-agent-that-makes-phone-calls",
      "similarity": 0.745648
    },
    {
      "slug": "ai-personal-assistant-appointment-booking",
      "similarity": 0.744557
    },
    {
      "slug": "instinct-ai-phone-calls",
      "similarity": 0.715197
    },
    {
      "slug": "openai-realtime-voices-phone-calls",
      "similarity": 0.69509
    },
    {
      "slug": "book-dinner-reservation-by-phone",
      "similarity": 0.688874
    },
    {
      "slug": "bland-ai-alternatives",
      "similarity": 0.660738
    },
    {
      "slug": "vercel-ai-sdk-phone-calls",
      "similarity": 0.65852
    },
    {
      "slug": "claude-code-phone-calls",
      "similarity": 0.650623
    }
  ],
  "ai-agent-that-makes-phone-calls": [
    {
      "slug": "vercel-ai-sdk-phone-calls",
      "similarity": 0.804191
    },
    {
      "slug": "instinct-ai-phone-calls",
      "similarity": 0.798701
    },
    {
      "slug": "openai-realtime-voices-phone-calls",
      "similarity": 0.798544
    },
    {
      "slug": "agent-web-research-phone-calls-sf-private-dining",
      "similarity": 0.745648
    },
    {
      "slug": "claude-code-phone-calls",
      "similarity": 0.743339
    },
    {
      "slug": "cascaded-voice-stack-vs-gpt-live",
      "similarity": 0.728463
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.707018
    },
    {
      "slug": "bland-ai-alternatives",
      "similarity": 0.705434
    }
  ],
  "ai-personal-assistant-appointment-booking": [
    {
      "slug": "mandarin-phone-call-scheduling",
      "similarity": 0.749489
    },
    {
      "slug": "reschedule-doctor-appointment",
      "similarity": 0.745613
    },
    {
      "slug": "agent-web-research-phone-calls-sf-private-dining",
      "similarity": 0.744557
    },
    {
      "slug": "book-dinner-reservation-by-phone",
      "similarity": 0.694747
    },
    {
      "slug": "running-late-to-appointment",
      "similarity": 0.690496
    },
    {
      "slug": "follow-up-appointment-telehealth",
      "similarity": 0.670663
    },
    {
      "slug": "customer-story-dental-appointments",
      "similarity": 0.632978
    }
  ],
  "ai-phone-tree-navigation": [
    {
      "slug": "twilio-mcp-phone-calls",
      "similarity": 0.801867
    },
    {
      "slug": "schedule-phone-calls-claude-code-codex",
      "similarity": 0.797743
    },
    {
      "slug": "phone-calling-mcp-comparison",
      "similarity": 0.777226
    },
    {
      "slug": "claude-code-phone-calls",
      "similarity": 0.741367
    },
    {
      "slug": "codex-phone-calls",
      "similarity": 0.738491
    },
    {
      "slug": "openai-realtime-voices-phone-calls",
      "similarity": 0.720596
    },
    {
      "slug": "t3-code-phone-calls",
      "similarity": 0.701629
    },
    {
      "slug": "muse-code-mcp-phone-calls",
      "similarity": 0.684942
    }
  ],
  "allstate-customer-service-number": [
    {
      "slug": "aaa-insurance-customer-service",
      "similarity": 0.699861
    },
    {
      "slug": "geico-customer-service",
      "similarity": 0.680688
    },
    {
      "slug": "unitedhealthcare-phone-number",
      "similarity": 0.62134
    },
    {
      "slug": "usaa-phone-number",
      "similarity": 0.612888
    }
  ],
  "amazon-pharmacy-phone-number": [
    {
      "slug": "how-to-transfer-a-prescription",
      "similarity": 0.670086
    }
  ],
  "american-airlines-flight-credit": [
    {
      "slug": "united-change-flight",
      "similarity": 0.656043
    },
    {
      "slug": "customer-story-flight-credit",
      "similarity": 0.637164
    },
    {
      "slug": "etihad-customer-service",
      "similarity": 0.622986
    }
  ],
  "aquasana-return-exception": [],
  "bland-ai-alternatives": [
    {
      "slug": "ai-agent-that-makes-phone-calls",
      "similarity": 0.705434
    },
    {
      "slug": "instinct-ai-phone-calls",
      "similarity": 0.682061
    },
    {
      "slug": "claude-code-phone-calls",
      "similarity": 0.674341
    },
    {
      "slug": "agent-web-research-phone-calls-sf-private-dining",
      "similarity": 0.660738
    },
    {
      "slug": "vapi-alternatives",
      "similarity": 0.659144
    },
    {
      "slug": "cascaded-voice-stack-vs-gpt-live",
      "similarity": 0.645466
    },
    {
      "slug": "vercel-ai-sdk-phone-calls",
      "similarity": 0.631005
    },
    {
      "slug": "openai-realtime-voices-phone-calls",
      "similarity": 0.620267
    }
  ],
  "book-dinner-reservation-by-phone": [
    {
      "slug": "customer-story-rick-dinner-reservation",
      "similarity": 0.712725
    },
    {
      "slug": "ai-personal-assistant-appointment-booking",
      "similarity": 0.694747
    },
    {
      "slug": "agent-web-research-phone-calls-sf-private-dining",
      "similarity": 0.688874
    },
    {
      "slug": "private-dining-room-cost",
      "similarity": 0.65722
    }
  ],
  "book-haircut-appointment": [
    {
      "slug": "running-late-to-barber",
      "similarity": 0.787512
    }
  ],
  "cancel-audible": [
    {
      "slug": "how-to-cancel-siriusxm",
      "similarity": 0.769827
    },
    {
      "slug": "cancel-planet-fitness",
      "similarity": 0.730684
    },
    {
      "slug": "cancel-factor",
      "similarity": 0.718364
    },
    {
      "slug": "cancel-crunch",
      "similarity": 0.707406
    },
    {
      "slug": "cancel-fubo",
      "similarity": 0.68403
    },
    {
      "slug": "cancel-la-fitness",
      "similarity": 0.661249
    },
    {
      "slug": "hulu-customer-service-number",
      "similarity": 0.657974
    },
    {
      "slug": "cancel-hellofresh",
      "similarity": 0.656605
    }
  ],
  "cancel-crunch": [
    {
      "slug": "cancel-la-fitness",
      "similarity": 0.908865
    },
    {
      "slug": "how-to-cancel-siriusxm",
      "similarity": 0.840042
    },
    {
      "slug": "cancel-planet-fitness",
      "similarity": 0.791928
    },
    {
      "slug": "cancel-hellofresh",
      "similarity": 0.725035
    },
    {
      "slug": "cancel-audible",
      "similarity": 0.707406
    },
    {
      "slug": "cancel-factor",
      "similarity": 0.706993
    },
    {
      "slug": "fabletics-customer-service",
      "similarity": 0.643524
    },
    {
      "slug": "gyms-with-sauna-near-me",
      "similarity": 0.609428
    }
  ],
  "cancel-factor": [
    {
      "slug": "cancel-hellofresh",
      "similarity": 0.798304
    },
    {
      "slug": "cancel-planet-fitness",
      "similarity": 0.730911
    },
    {
      "slug": "cancel-audible",
      "similarity": 0.718364
    },
    {
      "slug": "how-to-cancel-siriusxm",
      "similarity": 0.712482
    },
    {
      "slug": "cancel-crunch",
      "similarity": 0.706993
    },
    {
      "slug": "cancel-fubo",
      "similarity": 0.655278
    },
    {
      "slug": "cancel-la-fitness",
      "similarity": 0.650122
    },
    {
      "slug": "fabletics-customer-service",
      "similarity": 0.620788
    }
  ],
  "cancel-fubo": [
    {
      "slug": "cancel-audible",
      "similarity": 0.68403
    },
    {
      "slug": "cancel-hellofresh",
      "similarity": 0.669083
    },
    {
      "slug": "cancel-factor",
      "similarity": 0.655278
    },
    {
      "slug": "how-to-cancel-siriusxm",
      "similarity": 0.647649
    },
    {
      "slug": "cancel-planet-fitness",
      "similarity": 0.64761
    },
    {
      "slug": "directv-customer-service",
      "similarity": 0.646362
    },
    {
      "slug": "hulu-customer-service-number",
      "similarity": 0.643225
    },
    {
      "slug": "cancel-la-fitness",
      "similarity": 0.621413
    }
  ],
  "cancel-hellofresh": [
    {
      "slug": "cancel-factor",
      "similarity": 0.798304
    },
    {
      "slug": "cancel-crunch",
      "similarity": 0.725035
    },
    {
      "slug": "cancel-la-fitness",
      "similarity": 0.71116
    },
    {
      "slug": "cancel-planet-fitness",
      "similarity": 0.688412
    },
    {
      "slug": "how-to-cancel-siriusxm",
      "similarity": 0.675742
    },
    {
      "slug": "cancel-fubo",
      "similarity": 0.669083
    },
    {
      "slug": "hulu-customer-service-number",
      "similarity": 0.662263
    },
    {
      "slug": "cancel-audible",
      "similarity": 0.656605
    }
  ],
  "cancel-la-fitness": [
    {
      "slug": "cancel-crunch",
      "similarity": 0.908865
    },
    {
      "slug": "how-to-cancel-siriusxm",
      "similarity": 0.800584
    },
    {
      "slug": "cancel-planet-fitness",
      "similarity": 0.779216
    },
    {
      "slug": "cancel-hellofresh",
      "similarity": 0.71116
    },
    {
      "slug": "fabletics-customer-service",
      "similarity": 0.687841
    },
    {
      "slug": "cancel-audible",
      "similarity": 0.661249
    },
    {
      "slug": "cancel-factor",
      "similarity": 0.650122
    },
    {
      "slug": "gyms-with-sauna-near-me",
      "similarity": 0.636173
    }
  ],
  "cancel-planet-fitness": [
    {
      "slug": "cancel-crunch",
      "similarity": 0.791928
    },
    {
      "slug": "cancel-la-fitness",
      "similarity": 0.779216
    },
    {
      "slug": "how-to-cancel-siriusxm",
      "similarity": 0.741887
    },
    {
      "slug": "cancel-factor",
      "similarity": 0.730911
    },
    {
      "slug": "cancel-audible",
      "similarity": 0.730684
    },
    {
      "slug": "cancel-hellofresh",
      "similarity": 0.688412
    },
    {
      "slug": "cancel-fubo",
      "similarity": 0.64761
    },
    {
      "slug": "fabletics-customer-service",
      "similarity": 0.634147
    }
  ],
  "cascaded-voice-stack-vs-gpt-live": [
    {
      "slug": "openai-realtime-voices-phone-calls",
      "similarity": 0.793055
    },
    {
      "slug": "ai-agent-that-makes-phone-calls",
      "similarity": 0.728463
    },
    {
      "slug": "phone-calling-mcp-comparison",
      "similarity": 0.71375
    },
    {
      "slug": "grok-bot-vs-meta-muse",
      "similarity": 0.707673
    },
    {
      "slug": "instinct-ai-phone-calls",
      "similarity": 0.70033
    },
    {
      "slug": "ai-phone-tree-navigation",
      "similarity": 0.680091
    },
    {
      "slug": "vercel-ai-sdk-phone-calls",
      "similarity": 0.678817
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.674866
    }
  ],
  "claude-code-phone-calls": [
    {
      "slug": "schedule-phone-calls-claude-code-codex",
      "similarity": 0.787107
    },
    {
      "slug": "twilio-mcp-phone-calls",
      "similarity": 0.753154
    },
    {
      "slug": "ai-agent-that-makes-phone-calls",
      "similarity": 0.743339
    },
    {
      "slug": "ai-phone-tree-navigation",
      "similarity": 0.741367
    },
    {
      "slug": "phone-calling-mcp-comparison",
      "similarity": 0.739932
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.73616
    },
    {
      "slug": "t3-code-phone-calls",
      "similarity": 0.72356
    },
    {
      "slug": "codex-phone-calls",
      "similarity": 0.71673
    }
  ],
  "codex-phone-calls": [
    {
      "slug": "t3-code-phone-calls",
      "similarity": 0.82945
    },
    {
      "slug": "phone-calling-mcp-comparison",
      "similarity": 0.772739
    },
    {
      "slug": "twilio-mcp-phone-calls",
      "similarity": 0.769399
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.75509
    },
    {
      "slug": "ai-phone-tree-navigation",
      "similarity": 0.738491
    },
    {
      "slug": "openai-realtime-voices-phone-calls",
      "similarity": 0.729409
    },
    {
      "slug": "schedule-phone-calls-claude-code-codex",
      "similarity": 0.719989
    },
    {
      "slug": "claude-code-phone-calls",
      "similarity": 0.71673
    }
  ],
  "costco-eye-exam-cost": [
    {
      "slug": "eye-exam-cost-without-insurance",
      "similarity": 0.709457
    },
    {
      "slug": "how-much-does-blood-work-cost",
      "similarity": 0.668936
    },
    {
      "slug": "running-late-to-appointment",
      "similarity": 0.60358
    }
  ],
  "costco-tire-appointment-cancel-refund": [],
  "couch-reupholstery-cost": [
    {
      "slug": "furniture-refinishing-cost",
      "similarity": 0.906678
    },
    {
      "slug": "junk-removal-cost",
      "similarity": 0.650278
    }
  ],
  "customer-story-dental-appointments": [
    {
      "slug": "follow-up-appointment-telehealth",
      "similarity": 0.663111
    },
    {
      "slug": "reschedule-dentist-appointment",
      "similarity": 0.636452
    },
    {
      "slug": "ai-personal-assistant-appointment-booking",
      "similarity": 0.632978
    }
  ],
  "customer-story-flight-credit": [
    {
      "slug": "american-airlines-flight-credit",
      "similarity": 0.637164
    }
  ],
  "customer-story-joe-dress-shoes": [
    {
      "slug": "need-dress-shoes-today",
      "similarity": 0.729795
    },
    {
      "slug": "macys-bow-tie-stock-check",
      "similarity": 0.6512
    }
  ],
  "customer-story-rick-dinner-reservation": [
    {
      "slug": "book-dinner-reservation-by-phone",
      "similarity": 0.712725
    },
    {
      "slug": "private-dining-room-cost",
      "similarity": 0.671405
    },
    {
      "slug": "agent-web-research-phone-calls-sf-private-dining",
      "similarity": 0.639954
    }
  ],
  "delta-customer-service": [
    {
      "slug": "etihad-customer-service",
      "similarity": 0.647401
    }
  ],
  "directv-customer-service": [
    {
      "slug": "fabletics-customer-service",
      "similarity": 0.69159
    },
    {
      "slug": "hulu-customer-service-number",
      "similarity": 0.684769
    },
    {
      "slug": "how-to-cancel-siriusxm",
      "similarity": 0.662874
    },
    {
      "slug": "cancel-fubo",
      "similarity": 0.646362
    },
    {
      "slug": "cancel-hellofresh",
      "similarity": 0.639926
    },
    {
      "slug": "cancel-la-fitness",
      "similarity": 0.620714
    },
    {
      "slug": "spectrum-retention-department",
      "similarity": 0.611607
    },
    {
      "slug": "verizon-customer-service",
      "similarity": 0.609813
    }
  ],
  "dog-teeth-cleaning-cost": [
    {
      "slug": "veterinary-behavior-consultation-call",
      "similarity": 0.704433
    },
    {
      "slug": "drop-off-vet-appointment",
      "similarity": 0.629749
    }
  ],
  "doordash-customer-service-number": [
    {
      "slug": "cancel-hellofresh",
      "similarity": 0.637767
    }
  ],
  "drop-off-vet-appointment": [
    {
      "slug": "veterinary-behavior-consultation-call",
      "similarity": 0.725356
    },
    {
      "slug": "dog-teeth-cleaning-cost",
      "similarity": 0.629749
    }
  ],
  "etihad-customer-service": [
    {
      "slug": "delta-customer-service",
      "similarity": 0.647401
    },
    {
      "slug": "priceline-customer-service",
      "similarity": 0.646238
    },
    {
      "slug": "american-airlines-flight-credit",
      "similarity": 0.622986
    }
  ],
  "everything-we-have-improved-since-launch": [
    {
      "slug": "meta-muse-first-task",
      "similarity": 0.620394
    }
  ],
  "experian-phone-number": [
    {
      "slug": "usaa-phone-number",
      "similarity": 0.602155
    }
  ],
  "eye-exam-cost-without-insurance": [
    {
      "slug": "how-much-does-blood-work-cost",
      "similarity": 0.736028
    },
    {
      "slug": "costco-eye-exam-cost",
      "similarity": 0.709457
    }
  ],
  "fabletics-customer-service": [
    {
      "slug": "hulu-customer-service-number",
      "similarity": 0.723351
    },
    {
      "slug": "directv-customer-service",
      "similarity": 0.69159
    },
    {
      "slug": "cancel-la-fitness",
      "similarity": 0.687841
    },
    {
      "slug": "wayfair-customer-service",
      "similarity": 0.653133
    },
    {
      "slug": "cancel-audible",
      "similarity": 0.64699
    },
    {
      "slug": "how-to-cancel-siriusxm",
      "similarity": 0.644677
    },
    {
      "slug": "cancel-crunch",
      "similarity": 0.643524
    },
    {
      "slug": "cancel-hellofresh",
      "similarity": 0.638181
    }
  ],
  "fedex-customer-service-number": [
    {
      "slug": "ups-contact-number",
      "similarity": 0.707105
    }
  ],
  "fifth-third-bank-customer-service": [
    {
      "slug": "venmo-customer-service-number",
      "similarity": 0.634519
    }
  ],
  "follow-up-appointment-telehealth": [
    {
      "slug": "reschedule-doctor-appointment",
      "similarity": 0.784507
    },
    {
      "slug": "ai-personal-assistant-appointment-booking",
      "similarity": 0.670663
    },
    {
      "slug": "customer-story-dental-appointments",
      "similarity": 0.663111
    },
    {
      "slug": "reschedule-dentist-appointment",
      "similarity": 0.659237
    },
    {
      "slug": "how-to-find-a-new-primary-care-doctor",
      "similarity": 0.628693
    },
    {
      "slug": "running-late-to-appointment",
      "similarity": 0.624917
    }
  ],
  "fpl-phone-number": [],
  "furniture-refinishing-cost": [
    {
      "slug": "couch-reupholstery-cost",
      "similarity": 0.906678
    },
    {
      "slug": "junk-removal-cost",
      "similarity": 0.673814
    }
  ],
  "geico-customer-service": [
    {
      "slug": "allstate-customer-service-number",
      "similarity": 0.680688
    },
    {
      "slug": "aaa-insurance-customer-service",
      "similarity": 0.669445
    },
    {
      "slug": "unitedhealthcare-phone-number",
      "similarity": 0.649165
    },
    {
      "slug": "usaa-phone-number",
      "similarity": 0.603076
    }
  ],
  "grok-bot-reusable-skills": [
    {
      "slug": "grok-bot-template-troubleshooting",
      "similarity": 0.841983
    },
    {
      "slug": "grok-bot-templates",
      "similarity": 0.774309
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.773681
    },
    {
      "slug": "grok-bot-vs-meta-muse",
      "similarity": 0.765883
    },
    {
      "slug": "ai-agent-that-makes-phone-calls",
      "similarity": 0.676581
    },
    {
      "slug": "vercel-ai-sdk-phone-calls",
      "similarity": 0.660122
    },
    {
      "slug": "instinct-ai-phone-calls",
      "similarity": 0.647303
    },
    {
      "slug": "cascaded-voice-stack-vs-gpt-live",
      "similarity": 0.642589
    }
  ],
  "grok-bot-template-troubleshooting": [
    {
      "slug": "grok-bot-reusable-skills",
      "similarity": 0.841983
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.798916
    },
    {
      "slug": "grok-bot-templates",
      "similarity": 0.763294
    },
    {
      "slug": "grok-bot-vs-meta-muse",
      "similarity": 0.740644
    },
    {
      "slug": "claude-code-phone-calls",
      "similarity": 0.693552
    },
    {
      "slug": "ai-agent-that-makes-phone-calls",
      "similarity": 0.680906
    },
    {
      "slug": "schedule-phone-calls-claude-code-codex",
      "similarity": 0.650104
    },
    {
      "slug": "instinct-ai-phone-calls",
      "similarity": 0.644672
    }
  ],
  "grok-bot-templates": [
    {
      "slug": "grok-bot-reusable-skills",
      "similarity": 0.774309
    },
    {
      "slug": "grok-bot-template-troubleshooting",
      "similarity": 0.763294
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.753859
    },
    {
      "slug": "grok-bot-vs-meta-muse",
      "similarity": 0.736964
    },
    {
      "slug": "ai-agent-that-makes-phone-calls",
      "similarity": 0.661093
    },
    {
      "slug": "instinct-ai-phone-calls",
      "similarity": 0.659982
    },
    {
      "slug": "meta-muse-first-task",
      "similarity": 0.634193
    },
    {
      "slug": "openai-realtime-voices-phone-calls",
      "similarity": 0.632526
    }
  ],
  "grok-bot-vs-meta-muse": [
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.817182
    },
    {
      "slug": "grok-bot-reusable-skills",
      "similarity": 0.765883
    },
    {
      "slug": "grok-bot-template-troubleshooting",
      "similarity": 0.740644
    },
    {
      "slug": "grok-bot-templates",
      "similarity": 0.736964
    },
    {
      "slug": "meta-muse-first-task",
      "similarity": 0.733066
    },
    {
      "slug": "meta-muse-ai-agent-phone-calls",
      "similarity": 0.71639
    },
    {
      "slug": "cascaded-voice-stack-vs-gpt-live",
      "similarity": 0.707673
    },
    {
      "slug": "muse-code-mcp-phone-calls",
      "similarity": 0.700503
    }
  ],
  "grok-connectors-mcp-phone-calls": [
    {
      "slug": "grok-bot-vs-meta-muse",
      "similarity": 0.817182
    },
    {
      "slug": "grok-bot-template-troubleshooting",
      "similarity": 0.798916
    },
    {
      "slug": "grok-bot-reusable-skills",
      "similarity": 0.773681
    },
    {
      "slug": "t3-code-phone-calls",
      "similarity": 0.762346
    },
    {
      "slug": "twilio-mcp-phone-calls",
      "similarity": 0.758904
    },
    {
      "slug": "codex-phone-calls",
      "similarity": 0.75509
    },
    {
      "slug": "grok-bot-templates",
      "similarity": 0.753859
    },
    {
      "slug": "muse-code-mcp-phone-calls",
      "similarity": 0.749795
    }
  ],
  "gym-day-pass": [
    {
      "slug": "gyms-with-sauna-near-me",
      "similarity": 0.752682
    },
    {
      "slug": "cancel-la-fitness",
      "similarity": 0.620487
    },
    {
      "slug": "cancel-crunch",
      "similarity": 0.602484
    }
  ],
  "gyms-with-sauna-near-me": [
    {
      "slug": "gym-day-pass",
      "similarity": 0.752682
    },
    {
      "slug": "cancel-la-fitness",
      "similarity": 0.636173
    },
    {
      "slug": "cancel-crunch",
      "similarity": 0.609428
    }
  ],
  "hertz-customer-service-number": [
    {
      "slug": "priceline-customer-service",
      "similarity": 0.604421
    }
  ],
  "how-long-to-reach-a-human": [],
  "how-much-does-blood-work-cost": [
    {
      "slug": "eye-exam-cost-without-insurance",
      "similarity": 0.736028
    },
    {
      "slug": "costco-eye-exam-cost",
      "similarity": 0.668936
    }
  ],
  "how-to-cancel-siriusxm": [
    {
      "slug": "cancel-crunch",
      "similarity": 0.840042
    },
    {
      "slug": "cancel-la-fitness",
      "similarity": 0.800584
    },
    {
      "slug": "cancel-audible",
      "similarity": 0.769827
    },
    {
      "slug": "cancel-planet-fitness",
      "similarity": 0.741887
    },
    {
      "slug": "cancel-factor",
      "similarity": 0.712482
    },
    {
      "slug": "cancel-hellofresh",
      "similarity": 0.675742
    },
    {
      "slug": "directv-customer-service",
      "similarity": 0.662874
    },
    {
      "slug": "cancel-fubo",
      "similarity": 0.647649
    }
  ],
  "how-to-find-a-new-primary-care-doctor": [
    {
      "slug": "follow-up-appointment-telehealth",
      "similarity": 0.628693
    },
    {
      "slug": "reschedule-doctor-appointment",
      "similarity": 0.614724
    }
  ],
  "how-to-transfer-a-prescription": [
    {
      "slug": "amazon-pharmacy-phone-number",
      "similarity": 0.670086
    },
    {
      "slug": "adderall-shortage",
      "similarity": 0.610341
    }
  ],
  "hulu-customer-service-number": [
    {
      "slug": "fabletics-customer-service",
      "similarity": 0.723351
    },
    {
      "slug": "directv-customer-service",
      "similarity": 0.684769
    },
    {
      "slug": "cancel-hellofresh",
      "similarity": 0.662263
    },
    {
      "slug": "cancel-audible",
      "similarity": 0.657974
    },
    {
      "slug": "cancel-fubo",
      "similarity": 0.643225
    },
    {
      "slug": "how-to-cancel-siriusxm",
      "similarity": 0.638336
    },
    {
      "slug": "cancel-la-fitness",
      "similarity": 0.614758
    }
  ],
  "instinct-ai-phone-calls": [
    {
      "slug": "ai-agent-that-makes-phone-calls",
      "similarity": 0.798701
    },
    {
      "slug": "vercel-ai-sdk-phone-calls",
      "similarity": 0.746033
    },
    {
      "slug": "agent-web-research-phone-calls-sf-private-dining",
      "similarity": 0.715197
    },
    {
      "slug": "meta-muse-ai-agent-phone-calls",
      "similarity": 0.709263
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.708639
    },
    {
      "slug": "openai-realtime-voices-phone-calls",
      "similarity": 0.704765
    },
    {
      "slug": "cascaded-voice-stack-vs-gpt-live",
      "similarity": 0.70033
    },
    {
      "slug": "twilio-mcp-phone-calls",
      "similarity": 0.694326
    }
  ],
  "junk-removal-cost": [
    {
      "slug": "furniture-refinishing-cost",
      "similarity": 0.673814
    },
    {
      "slug": "couch-reupholstery-cost",
      "similarity": 0.650278
    }
  ],
  "lawyer-consultation-fee": [],
  "les-schwab-oil-change": [
    {
      "slug": "wheel-alignment-cost",
      "similarity": 0.766277
    },
    {
      "slug": "walmart-oil-change-prices",
      "similarity": 0.749782
    }
  ],
  "macys-bow-tie-stock-check": [
    {
      "slug": "customer-story-joe-dress-shoes",
      "similarity": 0.6512
    },
    {
      "slug": "need-dress-shoes-today",
      "similarity": 0.640336
    }
  ],
  "mandarin-phone-call-scheduling": [
    {
      "slug": "ai-personal-assistant-appointment-booking",
      "similarity": 0.749489
    }
  ],
  "meta-muse-ai-agent-phone-calls": [
    {
      "slug": "muse-code-mcp-phone-calls",
      "similarity": 0.930857
    },
    {
      "slug": "meta-muse-first-task",
      "similarity": 0.82718
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.736013
    },
    {
      "slug": "twilio-mcp-phone-calls",
      "similarity": 0.721087
    },
    {
      "slug": "grok-bot-vs-meta-muse",
      "similarity": 0.71639
    },
    {
      "slug": "instinct-ai-phone-calls",
      "similarity": 0.709263
    },
    {
      "slug": "phone-calling-mcp-comparison",
      "similarity": 0.70111
    },
    {
      "slug": "t3-code-phone-calls",
      "similarity": 0.693225
    }
  ],
  "meta-muse-first-task": [
    {
      "slug": "meta-muse-ai-agent-phone-calls",
      "similarity": 0.82718
    },
    {
      "slug": "muse-code-mcp-phone-calls",
      "similarity": 0.803269
    },
    {
      "slug": "grok-bot-vs-meta-muse",
      "similarity": 0.733066
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.663029
    },
    {
      "slug": "ai-agent-that-makes-phone-calls",
      "similarity": 0.658736
    },
    {
      "slug": "meta-muse-supplier-quotes",
      "similarity": 0.647238
    },
    {
      "slug": "openai-realtime-voices-phone-calls",
      "similarity": 0.644284
    },
    {
      "slug": "instinct-ai-phone-calls",
      "similarity": 0.640881
    }
  ],
  "meta-muse-supplier-quotes": [
    {
      "slug": "meta-muse-ai-agent-phone-calls",
      "similarity": 0.668127
    },
    {
      "slug": "meta-muse-first-task",
      "similarity": 0.647238
    },
    {
      "slug": "grok-bot-vs-meta-muse",
      "similarity": 0.636163
    },
    {
      "slug": "muse-code-mcp-phone-calls",
      "similarity": 0.630604
    }
  ],
  "muse-code-mcp-phone-calls": [
    {
      "slug": "meta-muse-ai-agent-phone-calls",
      "similarity": 0.930857
    },
    {
      "slug": "meta-muse-first-task",
      "similarity": 0.803269
    },
    {
      "slug": "twilio-mcp-phone-calls",
      "similarity": 0.762281
    },
    {
      "slug": "phone-calling-mcp-comparison",
      "similarity": 0.75772
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.749795
    },
    {
      "slug": "t3-code-phone-calls",
      "similarity": 0.748959
    },
    {
      "slug": "codex-phone-calls",
      "similarity": 0.704102
    },
    {
      "slug": "grok-bot-vs-meta-muse",
      "similarity": 0.700503
    }
  ],
  "need-dress-shoes-today": [
    {
      "slug": "customer-story-joe-dress-shoes",
      "similarity": 0.729795
    },
    {
      "slug": "macys-bow-tie-stock-check",
      "similarity": 0.640336
    }
  ],
  "ohio-workers-compensation-insurance": [],
  "openai-realtime-voices-phone-calls": [
    {
      "slug": "ai-agent-that-makes-phone-calls",
      "similarity": 0.798544
    },
    {
      "slug": "cascaded-voice-stack-vs-gpt-live",
      "similarity": 0.793055
    },
    {
      "slug": "codex-phone-calls",
      "similarity": 0.729409
    },
    {
      "slug": "ai-phone-tree-navigation",
      "similarity": 0.720596
    },
    {
      "slug": "instinct-ai-phone-calls",
      "similarity": 0.704765
    },
    {
      "slug": "vercel-ai-sdk-phone-calls",
      "similarity": 0.702023
    },
    {
      "slug": "agent-web-research-phone-calls-sf-private-dining",
      "similarity": 0.69509
    },
    {
      "slug": "claude-code-phone-calls",
      "similarity": 0.680441
    }
  ],
  "paypal-customer-service-number": [
    {
      "slug": "venmo-customer-service-number",
      "similarity": 0.67058
    }
  ],
  "phone-calling-mcp-comparison": [
    {
      "slug": "twilio-mcp-phone-calls",
      "similarity": 0.8697
    },
    {
      "slug": "schedule-phone-calls-claude-code-codex",
      "similarity": 0.782902
    },
    {
      "slug": "ai-phone-tree-navigation",
      "similarity": 0.777226
    },
    {
      "slug": "codex-phone-calls",
      "similarity": 0.772739
    },
    {
      "slug": "t3-code-phone-calls",
      "similarity": 0.767655
    },
    {
      "slug": "muse-code-mcp-phone-calls",
      "similarity": 0.75772
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.740261
    },
    {
      "slug": "claude-code-phone-calls",
      "similarity": 0.739932
    }
  ],
  "pottery-barn-customer-service": [
    {
      "slug": "wayfair-customer-service",
      "similarity": 0.696719
    },
    {
      "slug": "fabletics-customer-service",
      "similarity": 0.603007
    }
  ],
  "priceline-customer-service": [
    {
      "slug": "etihad-customer-service",
      "similarity": 0.646238
    },
    {
      "slug": "hertz-customer-service-number",
      "similarity": 0.604421
    }
  ],
  "private-dining-room-cost": [
    {
      "slug": "customer-story-rick-dinner-reservation",
      "similarity": 0.671405
    },
    {
      "slug": "book-dinner-reservation-by-phone",
      "similarity": 0.65722
    },
    {
      "slug": "agent-web-research-phone-calls-sf-private-dining",
      "similarity": 0.639106
    }
  ],
  "reschedule-dentist-appointment": [
    {
      "slug": "reschedule-doctor-appointment",
      "similarity": 0.718744
    },
    {
      "slug": "follow-up-appointment-telehealth",
      "similarity": 0.659237
    },
    {
      "slug": "customer-story-dental-appointments",
      "similarity": 0.636452
    }
  ],
  "reschedule-doctor-appointment": [
    {
      "slug": "follow-up-appointment-telehealth",
      "similarity": 0.784507
    },
    {
      "slug": "ai-personal-assistant-appointment-booking",
      "similarity": 0.745613
    },
    {
      "slug": "reschedule-dentist-appointment",
      "similarity": 0.718744
    },
    {
      "slug": "running-late-to-appointment",
      "similarity": 0.708862
    },
    {
      "slug": "how-to-find-a-new-primary-care-doctor",
      "similarity": 0.614724
    }
  ],
  "running-late-to-appointment": [
    {
      "slug": "reschedule-doctor-appointment",
      "similarity": 0.708862
    },
    {
      "slug": "ai-personal-assistant-appointment-booking",
      "similarity": 0.690496
    },
    {
      "slug": "follow-up-appointment-telehealth",
      "similarity": 0.624917
    },
    {
      "slug": "costco-eye-exam-cost",
      "similarity": 0.60358
    }
  ],
  "running-late-to-barber": [
    {
      "slug": "book-haircut-appointment",
      "similarity": 0.787512
    }
  ],
  "schedule-phone-calls-claude-code-codex": [
    {
      "slug": "twilio-mcp-phone-calls",
      "similarity": 0.806645
    },
    {
      "slug": "ai-phone-tree-navigation",
      "similarity": 0.797743
    },
    {
      "slug": "claude-code-phone-calls",
      "similarity": 0.787107
    },
    {
      "slug": "phone-calling-mcp-comparison",
      "similarity": 0.782902
    },
    {
      "slug": "codex-phone-calls",
      "similarity": 0.719989
    },
    {
      "slug": "t3-code-phone-calls",
      "similarity": 0.713228
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.705036
    },
    {
      "slug": "ai-agent-that-makes-phone-calls",
      "similarity": 0.702685
    }
  ],
  "spectrum-retention-department": [
    {
      "slug": "directv-customer-service",
      "similarity": 0.611607
    },
    {
      "slug": "windstream-customer-service",
      "similarity": 0.603799
    }
  ],
  "t3-code-phone-calls": [
    {
      "slug": "codex-phone-calls",
      "similarity": 0.82945
    },
    {
      "slug": "twilio-mcp-phone-calls",
      "similarity": 0.785475
    },
    {
      "slug": "phone-calling-mcp-comparison",
      "similarity": 0.767655
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.762346
    },
    {
      "slug": "muse-code-mcp-phone-calls",
      "similarity": 0.748959
    },
    {
      "slug": "claude-code-phone-calls",
      "similarity": 0.72356
    },
    {
      "slug": "schedule-phone-calls-claude-code-codex",
      "similarity": 0.713228
    },
    {
      "slug": "ai-phone-tree-navigation",
      "similarity": 0.701629
    }
  ],
  "twilio-mcp-phone-calls": [
    {
      "slug": "phone-calling-mcp-comparison",
      "similarity": 0.8697
    },
    {
      "slug": "schedule-phone-calls-claude-code-codex",
      "similarity": 0.806645
    },
    {
      "slug": "ai-phone-tree-navigation",
      "similarity": 0.801867
    },
    {
      "slug": "t3-code-phone-calls",
      "similarity": 0.785475
    },
    {
      "slug": "codex-phone-calls",
      "similarity": 0.769399
    },
    {
      "slug": "muse-code-mcp-phone-calls",
      "similarity": 0.762281
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.758904
    },
    {
      "slug": "claude-code-phone-calls",
      "similarity": 0.753154
    }
  ],
  "united-change-flight": [
    {
      "slug": "american-airlines-flight-credit",
      "similarity": 0.656043
    }
  ],
  "unitedhealthcare-phone-number": [
    {
      "slug": "geico-customer-service",
      "similarity": 0.649165
    },
    {
      "slug": "allstate-customer-service-number",
      "similarity": 0.62134
    },
    {
      "slug": "aaa-insurance-customer-service",
      "similarity": 0.616224
    }
  ],
  "ups-contact-number": [
    {
      "slug": "fedex-customer-service-number",
      "similarity": 0.707105
    }
  ],
  "usaa-phone-number": [
    {
      "slug": "aaa-insurance-customer-service",
      "similarity": 0.652481
    },
    {
      "slug": "allstate-customer-service-number",
      "similarity": 0.612888
    },
    {
      "slug": "geico-customer-service",
      "similarity": 0.603076
    },
    {
      "slug": "experian-phone-number",
      "similarity": 0.602155
    }
  ],
  "vapi-alternatives": [
    {
      "slug": "ai-phone-tree-navigation",
      "similarity": 0.675324
    },
    {
      "slug": "twilio-mcp-phone-calls",
      "similarity": 0.663938
    },
    {
      "slug": "phone-calling-mcp-comparison",
      "similarity": 0.661788
    },
    {
      "slug": "bland-ai-alternatives",
      "similarity": 0.659144
    },
    {
      "slug": "schedule-phone-calls-claude-code-codex",
      "similarity": 0.624342
    }
  ],
  "venmo-customer-service-number": [
    {
      "slug": "paypal-customer-service-number",
      "similarity": 0.67058
    },
    {
      "slug": "fifth-third-bank-customer-service",
      "similarity": 0.634519
    }
  ],
  "vercel-ai-sdk-phone-calls": [
    {
      "slug": "ai-agent-that-makes-phone-calls",
      "similarity": 0.804191
    },
    {
      "slug": "instinct-ai-phone-calls",
      "similarity": 0.746033
    },
    {
      "slug": "openai-realtime-voices-phone-calls",
      "similarity": 0.702023
    },
    {
      "slug": "ai-phone-tree-navigation",
      "similarity": 0.681377
    },
    {
      "slug": "grok-connectors-mcp-phone-calls",
      "similarity": 0.681309
    },
    {
      "slug": "cascaded-voice-stack-vs-gpt-live",
      "similarity": 0.678817
    },
    {
      "slug": "muse-code-mcp-phone-calls",
      "similarity": 0.677882
    },
    {
      "slug": "twilio-mcp-phone-calls",
      "similarity": 0.662794
    }
  ],
  "verizon-customer-service": [
    {
      "slug": "windstream-customer-service",
      "similarity": 0.611062
    },
    {
      "slug": "directv-customer-service",
      "similarity": 0.609813
    }
  ],
  "veterinary-behavior-consultation-call": [
    {
      "slug": "drop-off-vet-appointment",
      "similarity": 0.725356
    },
    {
      "slug": "dog-teeth-cleaning-cost",
      "similarity": 0.704433
    }
  ],
  "walmart-oil-change-prices": [
    {
      "slug": "wheel-alignment-cost",
      "similarity": 0.822895
    },
    {
      "slug": "les-schwab-oil-change",
      "similarity": 0.749782
    }
  ],
  "wayfair-customer-service": [
    {
      "slug": "pottery-barn-customer-service",
      "similarity": 0.696719
    },
    {
      "slug": "fabletics-customer-service",
      "similarity": 0.653133
    }
  ],
  "wheel-alignment-cost": [
    {
      "slug": "walmart-oil-change-prices",
      "similarity": 0.822895
    },
    {
      "slug": "les-schwab-oil-change",
      "similarity": 0.766277
    }
  ],
  "windstream-customer-service": [
    {
      "slug": "verizon-customer-service",
      "similarity": 0.611062
    },
    {
      "slug": "spectrum-retention-department",
      "similarity": 0.603799
    },
    {
      "slug": "directv-customer-service",
      "similarity": 0.601894
    }
  ],
  "wyoming-registered-agent-consent-form": []
};
