export interface CallExample {
  slug: string;
  title: string;
  business: string;
  date: string;
  request: string;
  outcome: string;
  audio: string;
  duration: string;
  transcript: TranscriptLine[];
}

/** Spoken turns follow the recording. Bracketed private details are replaced by silence. */
export type TranscriptLine =
  | { speaker: 'ai agent' | 'representative' | 'phone system'; text: string }
  | { note: string }
  | { cut: string };

/** Original conversations at normal speed, with private details muted. */
export const EXAMPLES: CallExample[] = [
  {
    slug: 'dinner-reservation',
    title: 'book a table for two',
    business: 'TAO Los Angeles',
    date: 'September 27, 2026',
    request: 'get a table for two tonight, around 8, under my name.',
    outcome: 'the restaurant confirmed a reservation for two at 8 pm.',
    audio: '/static/examples/dinner-reservation.mp3',
    duration: '1 minute 25 seconds',
    transcript: [
      { speaker: 'phone system', text: 'Thank you for calling TAO Restaurant Los Angeles. A concierge professional will be with you shortly.' },
      { note: 'the original wait music plays.' },
      { speaker: 'phone system', text: 'Your call may be recorded or transcribed by us or our service providers for system and quality training.' },
      { speaker: 'representative', text: 'Hi, thank you for calling TAO Los Angeles. My name is [name removed]. How can I help you guys tonight?' },
      { speaker: 'ai agent', text: 'Hi! I was hoping to get a table for two tonight, around eight?' },
      { speaker: 'representative', text: 'Let me see what we have available.' },
      { speaker: 'ai agent', text: 'Sure.' },
      { speaker: 'representative', text: 'Alrighty. It seems like we do have a table at eight available. Is this number the best number to put you down for a reservation?' },
      { speaker: 'ai agent', text: "Yeah, that's perfect. And the name is [name removed]." },
      { speaker: 'representative', text: 'Okay. I was able to pull up your OpenTable account. Do you have any dietary restrictions or special events tonight?' },
      { speaker: 'ai agent', text: 'No, neither tonight.' },
      { speaker: 'representative', text: "Alrighty. Well, I was able to make a reservation tonight at eight p.m. for two guests. We'll be seeing you guys soon." },
      { speaker: 'ai agent', text: 'Awesome. Thanks so much. Bye!' },
      { speaker: 'representative', text: 'Bye.' },
    ],
  },
  {
    slug: 'cancel-reservation',
    title: 'cancel a dinner reservation',
    business: 'TAO Los Angeles',
    date: 'September 27, 2026',
    request: "cancel tonight's reservation for two at 8 pm under my name. don't rebook.",
    outcome: 'the restaurant found two duplicate reservations and confirmed both were canceled. no new reservation was made.',
    audio: '/static/examples/cancel-reservation.mp3',
    duration: '1 minute 56 seconds',
    transcript: [
      { speaker: 'phone system', text: 'Thank you for calling TAO Restaurant Los Angeles. A concierge professional will be with you shortly.' },
      { note: 'the original wait music plays.' },
      { speaker: 'phone system', text: 'Your call may be recorded or transcribed by us or our service providers for system and quality training.' },
      { speaker: 'representative', text: 'Thank you for calling TAO LA. My name is [name removed]. How can I assist?' },
      { speaker: 'ai agent', text: "Hi [name removed], I'm calling cause I need to cancel a reservation for two tonight at eight under [name removed]." },
      { speaker: 'representative', text: 'Okay, no problem. Let me pull it up here.' },
      { speaker: 'ai agent', text: 'Thanks.' },
      { speaker: 'representative', text: "You're welcome." },
      { note: 'the host looks up the reservation.' },
      { speaker: 'representative', text: "Okay, it looks like I have two reservations for two people at eight o'clock. Did you need to cancel both?" },
      { speaker: 'ai agent', text: "Oh. Hmm. Yeah, I think that must've been a double booking. Yeah, please go ahead and cancel both." },
      { speaker: 'representative', text: "Yeah, no problem. They're, uh, you're all set. Um, I went ahead and canceled both of those." },
      { speaker: 'ai agent', text: 'Perfect. Thanks so much. Have a good one. Bye.' },
      { speaker: 'representative', text: 'You too, bye.' },
    ],
  },
  {
    slug: 'internet-availability',
    title: 'check home internet options',
    business: 'Monkeybrains',
    date: 'September 28, 2026',
    request: "check if they can serve my apartment (address and unit given), the plan, and the soonest installation. don't sign up.",
    outcome: 'the representative confirmed service was available, explained the plan and installation openings, and said property manager approval was needed. no installation was booked.',
    audio: '/static/examples/internet-availability.mp3',
    duration: '5 minutes 20 seconds',
    transcript: [
      { speaker: 'phone system', text: 'Welcome to Monkeybrains. For new residential service and scheduling, press one. For new commercial and event services, press five. For technical support, press two. For billing and account information, press three. For all other inquiries, press one.' },
      { speaker: 'ai agent', text: "Hmm. Let's try that one." },
      { speaker: 'representative', text: 'Monkeybrains, how can I help you?' },
      { speaker: 'ai agent', text: "Hey, I'm checking whether you can do residential internet at [address removed] in San Francisco, [ZIP code removed]." },
      { speaker: 'representative', text: 'Let me check. [address removed]. Is this for residential, you said?' },
      { speaker: 'ai agent', text: 'Yeah, just regular home internet.' },
      { speaker: 'representative', text: "Okay, let me take a look. Got it. So it looks like we haven't serviced this building before for residential. So, um, just make sure if you are not the owner that your property manager's okay with the installation and the external drilling." },
      { speaker: 'ai agent', text: 'Oh.' },
      { speaker: 'representative', text: 'And then let me take a look here. Have you been in contact with us over email? Oh, actually, I think I found it here. Did you say it was for unit [unit removed]?' },
      { speaker: 'ai agent', text: "Yeah, it's for unit [unit removed]." },
      { speaker: 'representative', text: 'Okay, for [name removed]?' },
      { speaker: 'ai agent', text: 'Yep, [name removed].' },
      { speaker: 'representative', text: "Got it. Okay, perfect. Let me put you on a quick hold. I'm just gonna check that we have a clear line of sight from this address to our towers in the area." },
      { speaker: 'ai agent', text: 'Sounds good.' },
      { speaker: 'representative', text: 'Hold on.' },
      { note: 'the original hold of about 90 seconds is included.' },
      { speaker: 'representative', text: 'Hi, thanks for holding there.' },
      { speaker: 'ai agent', text: 'Sure.' },
      { speaker: 'representative', text: "Okay, so we are able to service that building. So it's going to be one fifty for installation, and that does cover your first month of service. After that, it's going to be thirty five dollars a month. And we are month to month service with no long term contract, so you can cancel anytime. You're just gonna be responsible in regards to providing your own router and for setting that up yourself following our installation." },
      { speaker: 'ai agent', text: "Oh, that's great. And what kind of speeds are you usually seeing, and how soon could an install happen?" },
      { speaker: 'representative', text: 'Yeah, so for our standard residential plan, we offer a capacity of a hundred megabits per second for download and upload. And then you do have a thirty day cancellation policy, so if you do not like the service for whatever reason and you do cancel within thirty days of your installation, then you can get that one fifty back.' },
      { speaker: 'ai agent', text: 'Okay, and what would be the soonest you could do an install?' },
      { speaker: 'representative', text: 'Let me take a look.' },
      { note: 'the representative checks the schedule.' },
      { speaker: 'representative', text: 'Okay, so I did have some openings for tomorrow. I have a nine a.m., so we would arrive between nine and eleven a.m., as well as eleven a.m., so then they would arrive between eleven and one.' },
      { speaker: 'ai agent', text: "Awesome, that's really helpful. I'll check with the property manager and get back to you. Thanks so much for your help!" },
      { speaker: 'representative', text: 'Okay, sounds good. Yeah, no problem. Have a good day.' },
      { speaker: 'ai agent', text: 'You too! Bye!' },
    ],
  },
  {
    slug: 'expedite-review',
    title: 'get a stalled review moving',
    business: 'Amazon Pharmacy',
    date: 'September 28, 2026',
    request: 'three of my prescriptions have been stuck in pharmacist review for over a day. find out what is holding them up and ask support to move them along.',
    outcome: 'the representative agreed to mark the pending items as important. she estimated about an hour for review and said an email would follow when they were ready. this call does not confirm the review finished.',
    audio: '/static/examples/expedite-review.mp3',
    duration: '5 minutes 46 seconds',
    transcript: [
      { speaker: 'phone system', text: 'Thank you for calling Amazon Pharmacy and PillPack. If this is an emergency, please hang up and dial nine one one. All calls are recorded for quality and security. Are you an Amazon Pharmacy customer?' },
      { speaker: 'ai agent', text: 'Yes.' },
      { speaker: 'phone system', text: 'Is the mobile number you are calling from associated with your account?' },
      { speaker: 'ai agent', text: 'No.' },
      { speaker: 'phone system', text: 'One moment. No problem. Can you please tell me the mobile number linked to your Amazon Pharmacy account? You can speak it or enter it using your keypad followed by the pound key.' },
      { speaker: 'ai agent', text: "Yeah, it's [phone number removed]." },
      { speaker: 'phone system', text: 'I heard [phone number removed]. Is that correct?' },
      { speaker: 'ai agent', text: "That's correct." },
      { speaker: 'phone system', text: 'Thank you. Give me a moment.' },
      { speaker: 'ai agent', text: 'Sure, no problem.' },
      { speaker: 'phone system', text: "I've sent a six digit verification code. Go ahead whenever you're ready." },
      { speaker: 'ai agent', text: "Mm, let me check on that real quick. Yeah. Hmm. Okay. Okay, I've got it. It's [verification code removed]." },
      { speaker: 'phone system', text: 'Let me verify that for you.' },
      { speaker: 'ai agent', text: 'Sure thing.' },
      { speaker: 'phone system', text: 'Your code is correct. How can I help you today?' },
      { speaker: 'ai agent', text: "Hi, I'm trying to make sure three prescriptions under [name removed] move out of pharmacist review so they can be ordered today. They've been stuck for over twenty four hours." },
      { speaker: 'phone system', text: 'Let me check that for you. This will just take a moment.' },
      { speaker: 'ai agent', text: 'Sure, no problem.' },
      { speaker: 'phone system', text: "I can see three prescriptions in pharmacist review. [medication names removed]. All received on [date removed]. They're currently estimated to be ready by [date removed], but they can be expedited. Would you like me to request an expedited review for all three so they can be ready sooner?" },
      { speaker: 'ai agent', text: "Yeah, please. That would be great. And if there's anything blocking them, could you let me know what's needed?" },
      { speaker: 'phone system', text: "I'd be happy to help with that. However, I don't currently have an expedite tool available to me directly. I'll need to connect you with a customer care representative who can request the expedited review for all three prescriptions. [medication names removed]. One moment." },
      { speaker: 'ai agent', text: 'Okay, thanks!' },
      { speaker: 'phone system', text: 'The current wait time to speak with an Amazon Pharmacy customer care representative is approximately one minute. At the end of the call, you will have an opportunity to share your feedback in a brief customer satisfaction survey.' },
      { note: 'the original transfer wait is included.' },
      { speaker: 'representative', text: 'Clinical customer care. This is [name removed]. How can I help you?' },
      { speaker: 'ai agent', text: "Hey [name removed]! I'm calling because [name removed] has three prescriptions still under pharmacist review for over a day. Can you see what's blocking them and help move them along today?" },
      { speaker: 'representative', text: 'Yeah, absolutely.' },
      { note: 'the representative checks the account.' },
      { speaker: 'representative', text: 'What medications?' },
      { speaker: 'ai agent', text: 'There are [medication names and doses removed].' },
      { speaker: 'representative', text: "Okay, I'm not showing any issues. That's weird. Hold on." },
      { speaker: 'representative', text: "Oh, it does say in progress. Okay, I'll go ahead and mark them as important. Usually once that happens, they're done within like an hour." },
      { speaker: 'ai agent', text: 'Oh, nice! Okay.' },
      { speaker: 'representative', text: "Yeah, because I'm not sure why they haven't been done yet." },
      { speaker: 'ai agent', text: 'Yeah, it is a bit odd.' },
      { speaker: 'representative', text: "Yeah, but I'll mark them all as important." },
      { speaker: 'ai agent', text: "Okay, great! Do you know roughly what the prices will be once they're ready?" },
      { speaker: 'representative', text: 'I do not. That information is not available until after the PV one process.' },
      { speaker: 'ai agent', text: 'Gotcha. No worries.' },
      { speaker: 'representative', text: 'But the customer will get an email as soon as they are ready to order.' },
      { speaker: 'ai agent', text: 'Perfect, thanks so much!' },
      { speaker: 'representative', text: "Okay, you're welcome. Have a great day. Bye." },
      { cut: 'after the goodbye at 5:46, the remaining 24 minutes 9 seconds of the original recording contain an automated feedback survey and repeated survey prompts.' },
    ],
  },
  {
    slug: 'dentist-reschedule',
    title: 'reschedule a dentist appointment',
    business: 'a dental office',
    date: 'September 30, 2026',
    request: "move my thursday 3:30 appointment to friday after 3, or any time monday. i'd rather keep the same dentist.",
    outcome: 'the office moved the appointment to monday at noon with the same dentist, and confirmed it on the call.',
    audio: '/static/examples/dentist-reschedule.mp3',
    duration: '1 minute 58 seconds',
    transcript: [
      { speaker: 'representative', text: 'Hello, thank you for calling [practice name removed]. This is [name removed]. How can I help you?' },
      { speaker: 'ai agent', text: "Hi! This is Sarah, [name removed]'s assistant. I'm calling to see if we can move his Thursday [procedure removed] at three thirty to either Friday after three or anytime Monday." },
      { speaker: 'representative', text: 'Yeah, I can see, give me one second. What was the name one more time?' },
      { speaker: 'ai agent', text: '[name removed].' },
      { speaker: 'representative', text: 'Okay, let me see here. And you said something for Friday?' },
      { speaker: 'ai agent', text: 'Yeah, Friday after 3 would be great, or anytime Monday works too.' },
      { speaker: 'representative', text: "Okay, let me see here. Yeah, cause on Friday, Dr. [name removed] is not in office. Um, if you're okay seeing a different provider, but I could check for Monday what availability we have as well if he wanted to still see the same provider." },
      { speaker: 'ai agent', text: "Yeah, let's look at Monday instead. Preferably with the same provider, if you can." },
      { speaker: 'representative', text: 'Yeah. And then around what time did you say?' },
      { speaker: 'ai agent', text: 'Anytime Monday works, honestly.' },
      { speaker: 'representative', text: 'Okay, yeah, let me see what I have available. Give me one second here.' },
      { note: 'the receptionist checks the schedule.' },
      { speaker: 'representative', text: "Let's see. Would noon work for Monday, October 5th?" },
      { speaker: 'ai agent', text: 'Yeah, that would work. Can we move it to Monday, October 5th at noon?' },
      { speaker: 'representative', text: "Yeah. Okay, let me see here. Okay, perfect. I went ahead and rescheduled for Monday, October 5th at noon, and I already had called to confirm appointments for Monday already, so I'll go ahead and confirm his appointment here, and we have him all rescheduled." },
      { speaker: 'ai agent', text: 'Awesome. Thank you so much. That solves it. Thanks again, [name removed].' },
      { speaker: 'representative', text: 'Okay. Of course. Thank you. Bye-bye.' },
    ],
  },
  {
    slug: 'costco-tire-order',
    title: 'find an online tire order at the tire center',
    business: 'Costco San Francisco',
    date: 'September 30, 2026',
    request: "my costco.com tire order says it shipped weeks ago but i never got an arrival notice. find out if the tires are at the tire center and when the earliest install is. don't book anything.",
    outcome: 'after the order number was read back several times, the tire center found the order, confirmed the tires were there, and said the earliest installation was noon that day. no appointment was booked.',
    audio: '/static/examples/costco-tire-order.mp3',
    duration: '6 minutes 37 seconds',
    transcript: [
      { speaker: 'phone system', text: 'Thank you for calling the San Francisco Costco. To reach the administrative staff, press 1. For warehouse hours, directions, and holidays observed, press 2. For information on membership or returns, press 3. To reach the pharmacy, press 4. For all other departments, press 5.' },
      { note: 'the menu plays three times before the agent presses 5.' },
      { speaker: 'phone system', text: 'To reach the optical department, press 1. Hearing aid department, press 2. Food court pizza, press 3. Tire center, press 4. Bakery, press 5. Meat department, press 6. Service deli, press 7.' },
      { speaker: 'phone system', text: 'Please wait while I transfer your call.' },
      { note: 'the line rings.' },
      { speaker: 'representative', text: 'Hello, good day. How can I help you?' },
      { speaker: 'ai agent', text: "Hi, this is Sarah, the account owner's assistant. I'm calling about an order number [order number removed] for Michelin tires that were marked shipped September 14th. But we haven't gotten an arrival notice. Could you check if those have arrived?" },
      { speaker: 'representative', text: 'Okay, hold on. Can you give me the item number one more time to check on the computer?' },
      { speaker: 'ai agent', text: 'Yeah, for sure. [order number removed]' },
      { speaker: 'representative', text: '[order number removed]. Okay, hold on.' },
      { note: 'the tire center staff talk among themselves while checking. their side conversation is left as is.' },
      { speaker: 'representative', text: 'Okay, and you ordered tires and you were checking to see if the tires came in?' },
      { speaker: 'ai agent', text: 'Exactly.' },
      { speaker: 'representative', text: 'Okay. Do you have your order number or your membership number?' },
      { speaker: 'ai agent', text: "I do have the order number. That's [order number removed]" },
      { speaker: 'representative', text: 'Okay, give me one second. So you ordered them online?' },
      { speaker: 'ai agent', text: 'Yeah, it was online.' },
      { note: 'the order number is read back and forth several times. each reading is muted.' },
      { speaker: 'representative', text: "Okay, so unfortunately I don't have an order under that order number." },
      { speaker: 'ai agent', text: 'Oh, okay. All right. Do you need the membership number to find it, or could you look it up by the member name? [name removed]' },
      { cut: "the agent's last words overlap the representative's reply, so both are muted. she said she could look it up by the membership number." },
      { note: 'the staff check again among themselves.' },
      { speaker: 'ai agent', text: 'Thanks for hanging on. Just to clarify, the full order number is [order number removed].' },
      { speaker: 'representative', text: "Okay, hold on. I'm not even by a computer, sorry, and I was going to look up your membership, so you're going to have to bear with me. I've got to set up for a different thing, so... All right, so you said [order number removed]" },
      { speaker: 'representative', text: "All right, so yeah, your order is here, and yeah, you're good. Do you want me to schedule your appointment for them to be installed?" },
      { speaker: 'ai agent', text: 'No need to schedule it, but could you just tell me the earliest installation appointment you have available?' },
      { speaker: 'representative', text: "Yeah. My earliest installation would be... My earliest installation would be 12 o'clock today." },
      { speaker: 'ai agent', text: "Okay, perfect. That's great to know. Thanks so much for your help. Bye!" },
      { speaker: 'representative', text: 'No problem.' },
    ],
  },
  {
    slug: 'junk-removal-booking',
    title: 'get a junk removal quote and book the pickup',
    business: 'A1 Hauling, San Francisco',
    date: 'September 30, 2026',
    request: "get a price to haul a small load of empty cardboard boxes from our office, and book the earliest pickup if it's under $500 all in. it's just boxes, so push for the minimum load price.",
    outcome: 'the hauler quoted about $140 and booked the pickup for 11 am the next day. it read the street number back wrong, and the agent agreed by mistake. a second call fixed the address.',
    audio: '/static/examples/junk-removal-booking.mp3',
    duration: '3 minutes 13 seconds',
    transcript: [
      { speaker: 'representative', text: 'A1 Hauling.' },
      { speaker: 'ai agent', text: "Hi! This is Sarah, [name removed]'s assistant. I am wondering about a quote for picking up some cardboard boxes from our office, please." },
      { speaker: 'representative', text: 'Sure, what city are you in?' },
      { speaker: 'ai agent', text: 'San Francisco.' },
      { speaker: 'representative', text: 'Okay, and you say it has a lot of boxes?' },
      { speaker: 'ai agent', text: "Yeah, it's just a small load. Five chair boxes, a couple TV boxes, and a handful of smaller ones." },
      { speaker: 'representative', text: 'Okay, and when are you looking to do it?' },
      { speaker: 'ai agent', text: 'Anytime. Earliest available is best.' },
      { speaker: 'representative', text: 'Okay, we could do it tomorrow, around 11 in the morning.' },
      { speaker: 'ai agent', text: 'Oh, nice. That could work. What would the price be for a load like that?' },
      { speaker: 'representative', text: 'Okay. Is that at a house, or?' },
      { speaker: 'ai agent', text: "It's at a commercial office building. There's a freight elevator. It's on the third floor." },
      { speaker: 'representative', text: "Oh, there's a freight elevator. Okay. Well, about 140 should do." },
      { speaker: 'ai agent', text: 'Perfect.' },
      { speaker: 'representative', text: "And I'm sorry, what's your name?" },
      { speaker: 'ai agent', text: 'That works great. Can we lock in tomorrow at around 11 then?' },
      { speaker: 'representative', text: 'Sure. Give me just one second.' },
      { speaker: 'representative', text: 'Are you there?' },
      { speaker: 'ai agent', text: "Yeah, I'm here. Could we lock in tomorrow around 11 then?" },
      { speaker: 'representative', text: "Sure. Okay. 11 o'clock tomorrow. And what's the address?" },
      { speaker: 'ai agent', text: '[address removed], San Francisco.' },
      { speaker: 'representative', text: "I'm sorry, [address removed]?" },
      { note: 'he reads back the wrong street number.' },
      { speaker: 'ai agent', text: 'Exactly. Yeah.' },
      { speaker: 'representative', text: "I'm sorry, I'm talking to an AI or a human? I'm sorry." },
      { speaker: 'ai agent', text: "Yeah, I'm an AI assistant helping [name removed] out." },
      { speaker: 'representative', text: "Oh, Jesus, because I'm a little confused here. Okay, I got it. Your number is [phone number removed]?" },
      { speaker: 'ai agent', text: "That's exactly right. [phone number removed]." },
      { speaker: 'representative', text: 'Okay, who is the person I should ask?' },
      { speaker: 'ai agent', text: "Sorry, I didn't catch that." },
      { speaker: 'representative', text: 'I just need a name of a person.' },
      { speaker: 'ai agent', text: 'Sure. [name removed].' },
      { speaker: 'representative', text: '[name removed]?' },
      { speaker: 'ai agent', text: '[name removed, then spelled out].' },
      { speaker: 'representative', text: "Okay, it's all confirmed. Tomorrow at 11 a.m. It's [address removed]." },
      { speaker: 'ai agent', text: 'Perfect. Thanks so much. Take care. Bye.' },
      { speaker: 'representative', text: "You're welcome. Bye-bye." },
    ],
  },
];
