export interface CallExample {
  slug: string;
  title: string;
  business: string;
  date: string;
  request: string;
  outcome: string;
  audio: string;
  duration: string;
  transcript: TranscriptLine[];
}

/** Spoken turns follow the recording. Bracketed private details are replaced by silence. */
export type TranscriptLine =
  | { speaker: 'ai agent' | 'representative' | 'phone system'; text: string }
  | { note: string }
  | { cut: string };

/** Original conversations at normal speed, with private details muted. */
export const EXAMPLES: CallExample[] = [
  {
    slug: 'dinner-reservation',
    title: 'book a table for two',
    business: 'TAO Los Angeles',
    date: 'September 27, 2026',
    request: 'get a table for two tonight, around 8, under my name.',
    outcome: 'the restaurant confirmed a reservation for two at 8 pm.',
    audio: '/static/examples/dinner-reservation.mp3',
    duration: '1 minute 25 seconds',
    transcript: [
      { speaker: 'phone system', text: 'Thank you for calling TAO Restaurant Los Angeles. A concierge professional will be with you shortly.' },
      { note: 'the original wait music plays.' },
      { speaker: 'phone system', text: 'Your call may be recorded or transcribed by us or our service providers for system and quality training.' },
      { speaker: 'representative', text: 'Hi, thank you for calling TAO Los Angeles. My name is [name removed]. How can I help you guys tonight?' },
      { speaker: 'ai agent', text: 'Hi! I was hoping to get a table for two tonight, around eight?' },
      { speaker: 'representative', text: 'Let me see what we have available.' },
      { speaker: 'ai agent', text: 'Sure.' },
      { speaker: 'representative', text: 'Alrighty. It seems like we do have a table at eight available. Is this number the best number to put you down for a reservation?' },
      { speaker: 'ai agent', text: "Yeah, that's perfect. And the name is [name removed]." },
      { speaker: 'representative', text: 'Okay. I was able to pull up your OpenTable account. Do you have any dietary restrictions or special events tonight?' },
      { speaker: 'ai agent', text: 'No, neither tonight.' },
      { speaker: 'representative', text: "Alrighty. Well, I was able to make a reservation tonight at eight p.m. for two guests. We'll be seeing you guys soon." },
      { speaker: 'ai agent', text: 'Awesome. Thanks so much. Bye!' },
      { speaker: 'representative', text: 'Bye.' },
    ],
  },
  {
    slug: 'cancel-reservation',
    title: 'cancel a dinner reservation',
    business: 'TAO Los Angeles',
    date: 'September 27, 2026',
    request: "cancel tonight's reservation for two at 8 pm under my name. don't rebook.",
    outcome: 'the restaurant found two duplicate reservations and confirmed both were canceled. no new reservation was made.',
    audio: '/static/examples/cancel-reservation.mp3',
    duration: '1 minute 56 seconds',
    transcript: [
      { speaker: 'phone system', text: 'Thank you for calling TAO Restaurant Los Angeles. A concierge professional will be with you shortly.' },
      { note: 'the original wait music plays.' },
      { speaker: 'phone system', text: 'Your call may be recorded or transcribed by us or our service providers for system and quality training.' },
      { speaker: 'representative', text: 'Thank you for calling TAO LA. My name is [name removed]. How can I assist?' },
      { speaker: 'ai agent', text: "Hi [name removed], I'm calling cause I need to cancel a reservation for two tonight at eight under [name removed]." },
      { speaker: 'representative', text: 'Okay, no problem. Let me pull it up here.' },
      { speaker: 'ai agent', text: 'Thanks.' },
      { speaker: 'representative', text: "You're welcome." },
      { note: 'the host looks up the reservation.' },
      { speaker: 'representative', text: "Okay, it looks like I have two reservations for two people at eight o'clock. Did you need to cancel both?" },
      { speaker: 'ai agent', text: "Oh. Hmm. Yeah, I think that must've been a double booking. Yeah, please go ahead and cancel both." },
      { speaker: 'representative', text: "Yeah, no problem. They're, uh, you're all set. Um, I went ahead and canceled both of those." },
      { speaker: 'ai agent', text: 'Perfect. Thanks so much. Have a good one. Bye.' },
      { speaker: 'representative', text: 'You too, bye.' },
    ],
  },
  {
    slug: 'internet-availability',
    title: 'check home internet options',
    business: 'Monkeybrains',
    date: 'September 28, 2026',
    request: "check if they can serve my apartment (address and unit given), the plan, and the soonest installation. don't sign up.",
    outcome: 'the representative confirmed service was available, explained the plan and installation openings, and said property manager approval was needed. no installation was booked.',
    audio: '/static/examples/internet-availability.mp3',
    duration: '5 minutes 20 seconds',
    transcript: [
      { speaker: 'phone system', text: 'Welcome to Monkeybrains. For new residential service and scheduling, press one. For new commercial and event services, press five. For technical support, press two. For billing and account information, press three. For all other inquiries, press one.' },
      { speaker: 'ai agent', text: "Hmm. Let's try that one." },
      { speaker: 'representative', text: 'Monkeybrains, how can I help you?' },
      { speaker: 'ai agent', text: "Hey, I'm checking whether you can do residential internet at [address removed] in San Francisco, [ZIP code removed]." },
      { speaker: 'representative', text: 'Let me check. [address removed]. Is this for residential, you said?' },
      { speaker: 'ai agent', text: 'Yeah, just regular home internet.' },
      { speaker: 'representative', text: "Okay, let me take a look. Got it. So it looks like we haven't serviced this building before for residential. So, um, just make sure if you are not the owner that your property manager's okay with the installation and the external drilling." },
      { speaker: 'ai agent', text: 'Oh.' },
      { speaker: 'representative', text: 'And then let me take a look here. Have you been in contact with us over email? Oh, actually, I think I found it here. Did you say it was for unit [unit removed]?' },
      { speaker: 'ai agent', text: "Yeah, it's for unit [unit removed]." },
      { speaker: 'representative', text: 'Okay, for [name removed]?' },
      { speaker: 'ai agent', text: 'Yep, [name removed].' },
      { speaker: 'representative', text: "Got it. Okay, perfect. Let me put you on a quick hold. I'm just gonna check that we have a clear line of sight from this address to our towers in the area." },
      { speaker: 'ai agent', text: 'Sounds good.' },
      { speaker: 'representative', text: 'Hold on.' },
      { note: 'the original hold of about 90 seconds is included.' },
      { speaker: 'representative', text: 'Hi, thanks for holding there.' },
      { speaker: 'ai agent', text: 'Sure.' },
      { speaker: 'representative', text: "Okay, so we are able to service that building. So it's going to be one fifty for installation, and that does cover your first month of service. After that, it's going to be thirty five dollars a month. And we are month to month service with no long term contract, so you can cancel anytime. You're just gonna be responsible in regards to providing your own router and for setting that up yourself following our installation." },
      { speaker: 'ai agent', text: "Oh, that's great. And what kind of speeds are you usually seeing, and how soon could an install happen?" },
      { speaker: 'representative', text: 'Yeah, so for our standard residential plan, we offer a capacity of a hundred megabits per second for download and upload. And then you do have a thirty day cancellation policy, so if you do not like the service for whatever reason and you do cancel within thirty days of your installation, then you can get that one fifty back.' },
      { speaker: 'ai agent', text: 'Okay, and what would be the soonest you could do an install?' },
      { speaker: 'representative', text: 'Let me take a look.' },
      { note: 'the representative checks the schedule.' },
      { speaker: 'representative', text: 'Okay, so I did have some openings for tomorrow. I have a nine a.m., so we would arrive between nine and eleven a.m., as well as eleven a.m., so then they would arrive between eleven and one.' },
      { speaker: 'ai agent', text: "Awesome, that's really helpful. I'll check with the property manager and get back to you. Thanks so much for your help!" },
      { speaker: 'representative', text: 'Okay, sounds good. Yeah, no problem. Have a good day.' },
      { speaker: 'ai agent', text: 'You too! Bye!' },
    ],
  },
  {
    slug: 'expedite-review',
    title: 'get a stalled review moving',
    business: 'Amazon Pharmacy',
    date: 'September 28, 2026',
    request: 'three of my prescriptions have been stuck in pharmacist review for over a day. find out what is holding them up and ask support to move them along.',
    outcome: 'the representative agreed to mark the pending items as important. she estimated about an hour for review and said an email would follow when they were ready. this call does not confirm the review finished.',
    audio: '/static/examples/expedite-review.mp3',
    duration: '5 minutes 46 seconds',
    transcript: [
      { speaker: 'phone system', text: 'Thank you for calling Amazon Pharmacy and PillPack. If this is an emergency, please hang up and dial nine one one. All calls are recorded for quality and security. Are you an Amazon Pharmacy customer?' },
      { speaker: 'ai agent', text: 'Yes.' },
      { speaker: 'phone system', text: 'Is the mobile number you are calling from associated with your account?' },
      { speaker: 'ai agent', text: 'No.' },
      { speaker: 'phone system', text: 'One moment. No problem. Can you please tell me the mobile number linked to your Amazon Pharmacy account? You can speak it or enter it using your keypad followed by the pound key.' },
      { speaker: 'ai agent', text: "Yeah, it's [phone number removed]." },
      { speaker: 'phone system', text: 'I heard [phone number removed]. Is that correct?' },
      { speaker: 'ai agent', text: "That's correct." },
      { speaker: 'phone system', text: 'Thank you. Give me a moment.' },
      { speaker: 'ai agent', text: 'Sure, no problem.' },
      { speaker: 'phone system', text: "I've sent a six digit verification code. Go ahead whenever you're ready." },
      { speaker: 'ai agent', text: "Mm, let me check on that real quick. Yeah. Hmm. Okay. Okay, I've got it. It's [verification code removed]." },
      { speaker: 'phone system', text: 'Let me verify that for you.' },
      { speaker: 'ai agent', text: 'Sure thing.' },
      { speaker: 'phone system', text: 'Your code is correct. How can I help you today?' },
      { speaker: 'ai agent', text: "Hi, I'm trying to make sure three prescriptions under [name removed] move out of pharmacist review so they can be ordered today. They've been stuck for over twenty four hours." },
      { speaker: 'phone system', text: 'Let me check that for you. This will just take a moment.' },
      { speaker: 'ai agent', text: 'Sure, no problem.' },
      { speaker: 'phone system', text: "I can see three prescriptions in pharmacist review. [medication names removed]. All received on [date removed]. They're currently estimated to be ready by [date removed], but they can be expedited. Would you like me to request an expedited review for all three so they can be ready sooner?" },
      { speaker: 'ai agent', text: "Yeah, please. That would be great. And if there's anything blocking them, could you let me know what's needed?" },
      { speaker: 'phone system', text: "I'd be happy to help with that. However, I don't currently have an expedite tool available to me directly. I'll need to connect you with a customer care representative who can request the expedited review for all three prescriptions. [medication names removed]. One moment." },
      { speaker: 'ai agent', text: 'Okay, thanks!' },
      { speaker: 'phone system', text: 'The current wait time to speak with an Amazon Pharmacy customer care representative is approximately one minute. At the end of the call, you will have an opportunity to share your feedback in a brief customer satisfaction survey.' },
      { note: 'the original transfer wait is included.' },
      { speaker: 'representative', text: 'Clinical customer care. This is [name removed]. How can I help you?' },
      { speaker: 'ai agent', text: "Hey [name removed]! I'm calling because [name removed] has three prescriptions still under pharmacist review for over a day. Can you see what's blocking them and help move them along today?" },
      { speaker: 'representative', text: 'Yeah, absolutely.' },
      { note: 'the representative checks the account.' },
      { speaker: 'representative', text: 'What medications?' },
      { speaker: 'ai agent', text: 'There are [medication names and doses removed].' },
      { speaker: 'representative', text: "Okay, I'm not showing any issues. That's weird. Hold on." },
      { speaker: 'representative', text: "Oh, it does say in progress. Okay, I'll go ahead and mark them as important. Usually once that happens, they're done within like an hour." },
      { speaker: 'ai agent', text: 'Oh, nice! Okay.' },
      { speaker: 'representative', text: "Yeah, because I'm not sure why they haven't been done yet." },
      { speaker: 'ai agent', text: 'Yeah, it is a bit odd.' },
      { speaker: 'representative', text: "Yeah, but I'll mark them all as important." },
      { speaker: 'ai agent', text: "Okay, great! Do you know roughly what the prices will be once they're ready?" },
      { speaker: 'representative', text: 'I do not. That information is not available until after the PV one process.' },
      { speaker: 'ai agent', text: 'Gotcha. No worries.' },
      { speaker: 'representative', text: 'But the customer will get an email as soon as they are ready to order.' },
      { speaker: 'ai agent', text: 'Perfect, thanks so much!' },
      { speaker: 'representative', text: "Okay, you're welcome. Have a great day. Bye." },
      { cut: 'after the goodbye at 5:46, the remaining 24 minutes 9 seconds of the original recording contain an automated feedback survey and repeated survey prompts.' },
    ],
  },
  {
    slug: 'dentist-reschedule',
    title: 'reschedule a dentist appointment',
    business: 'a dental office',
    date: 'September 30, 2026',
    request: "move my thursday 3:30 appointment to friday after 3, or any time monday. i'd rather keep the same dentist.",
    outcome: 'the office moved the appointment to monday at noon with the same dentist, and confirmed it on the call.',
    audio: '/static/examples/dentist-reschedule.mp3',
    duration: '1 minute 58 seconds',
    transcript: [
      { speaker: 'representative', text: 'Hello, thank you for calling [practice name removed]. This is [name removed]. How can I help you?' },
      { speaker: 'ai agent', text: "Hi! This is Sarah, [name removed]'s assistant. I'm calling to see if we can move his Thursday [procedure removed] at three thirty to either Friday after three or anytime Monday." },
      { speaker: 'representative', text: 'Yeah, I can see, give me one second. What was the name one more time?' },
      { speaker: 'ai agent', text: '[name removed].' },
      { speaker: 'representative', text: 'Okay, let me see here. And you said something for Friday?' },
      { speaker: 'ai agent', text: 'Yeah, Friday after 3 would be great, or anytime Monday works too.' },
      { speaker: 'representative', text: "Okay, let me see here. Yeah, cause on Friday, Dr. [name removed] is not in office. Um, if you're okay seeing a different provider, but I could check for Monday what availability we have as well if he wanted to still see the same provider." },
      { speaker: 'ai agent', text: "Yeah, let's look at Monday instead. Preferably with the same provider, if you can." },
      { speaker: 'representative', text: 'Yeah. And then around what time did you say?' },
      { speaker: 'ai agent', text: 'Anytime Monday works, honestly.' },
      { speaker: 'representative', text: 'Okay, yeah, let me see what I have available. Give me one second here.' },
      { note: 'the receptionist checks the schedule.' },
      { speaker: 'representative', text: "Let's see. Would noon work for Monday, October 5th?" },
      { speaker: 'ai agent', text: 'Yeah, that would work. Can we move it to Monday, October 5th at noon?' },
      { speaker: 'representative', text: "Yeah. Okay, let me see here. Okay, perfect. I went ahead and rescheduled for Monday, October 5th at noon, and I already had called to confirm appointments for Monday already, so I'll go ahead and confirm his appointment here, and we have him all rescheduled." },
      { speaker: 'ai agent', text: 'Awesome. Thank you so much. That solves it. Thanks again, [name removed].' },
      { speaker: 'representative', text: 'Okay. Of course. Thank you. Bye-bye.' },
    ],
  },
  {
    slug: 'costco-tire-order',
    title: 'find an online tire order at the tire center',
    business: 'Costco San Francisco',
    date: 'September 30, 2026',
    request: "my costco.com tire order says it shipped weeks ago but i never got an arrival notice. find out if the tires are at the tire center and when the earliest install is. don't book anything.",
    outcome: 'after the order number was read back several times, the tire center found the order, confirmed the tires were there, and said the earliest installation was noon that day. no appointment was booked.',
    audio: '/static/examples/costco-tire-order.mp3',
    duration: '6 minutes 37 seconds',
    transcript: [
      { speaker: 'phone system', text: 'Thank you for calling the San Francisco Costco. To reach the administrative staff, press 1. For warehouse hours, directions, and holidays observed, press 2. For information on membership or returns, press 3. To reach the pharmacy, press 4. For all other departments, press 5.' },
      { note: 'the menu plays three times before the agent presses 5.' },
      { speaker: 'phone system', text: 'To reach the optical department, press 1. Hearing aid department, press 2. Food court pizza, press 3. Tire center, press 4. Bakery, press 5. Meat department, press 6. Service deli, press 7.' },
      { speaker: 'phone system', text: 'Please wait while I transfer your call.' },
      { note: 'the line rings.' },
      { speaker: 'representative', text: 'Hello, good day. How can I help you?' },
      { speaker: 'ai agent', text: "Hi, this is Sarah, the account owner's assistant. I'm calling about an order number [order number removed] for Michelin tires that were marked shipped September 14th. But we haven't gotten an arrival notice. Could you check if those have arrived?" },
      { speaker: 'representative', text: 'Okay, hold on. Can you give me the item number one more time to check on the computer?' },
      { speaker: 'ai agent', text: 'Yeah, for sure. [order number removed]' },
      { speaker: 'representative', text: '[order number removed]. Okay, hold on.' },
      { note: 'the tire center staff talk among themselves while checking. their side conversation is left as is.' },
      { speaker: 'representative', text: 'Okay, and you ordered tires and you were checking to see if the tires came in?' },
      { speaker: 'ai agent', text: 'Exactly.' },
      { speaker: 'representative', text: 'Okay. Do you have your order number or your membership number?' },
      { speaker: 'ai agent', text: "I do have the order number. That's [order number removed]" },
      { speaker: 'representative', text: 'Okay, give me one second. So you ordered them online?' },
      { speaker: 'ai agent', text: 'Yeah, it was online.' },
      { note: 'the order number is read back and forth several times. each reading is muted.' },
      { speaker: 'representative', text: "Okay, so unfortunately I don't have an order under that order number." },
      { speaker: 'ai agent', text: 'Oh, okay. All right. Do you need the membership number to find it, or could you look it up by the member name? [name removed]' },
      { cut: "the agent's last words overlap the representative's reply, so both are muted. she said she could look it up by the membership number." },
      { note: 'the staff check again among themselves.' },
      { speaker: 'ai agent', text: 'Thanks for hanging on. Just to clarify, the full order number is [order number removed].' },
      { speaker: 'representative', text: "Okay, hold on. I'm not even by a computer, sorry, and I was going to look up your membership, so you're going to have to bear with me. I've got to set up for a different thing, so... All right, so you said [order number removed]" },
      { speaker: 'representative', text: "All right, so yeah, your order is here, and yeah, you're good. Do you want me to schedule your appointment for them to be installed?" },
      { speaker: 'ai agent', text: 'No need to schedule it, but could you just tell me the earliest installation appointment you have available?' },
      { speaker: 'representative', text: "Yeah. My earliest installation would be... My earliest installation would be 12 o'clock today." },
      { speaker: 'ai agent', text: "Okay, perfect. That's great to know. Thanks so much for your help. Bye!" },
      { speaker: 'representative', text: 'No problem.' },
    ],
  },
  {
    slug: 'junk-removal-booking',
    title: 'get a junk removal quote and book the pickup',
    business: 'A1 Hauling, San Francisco',
    date: 'September 30, 2026',
    request: "get a price to haul a small load of empty cardboard boxes from our office, and book the earliest pickup if it's under $500 all in. it's just boxes, so push for the minimum load price.",
    outcome: 'the hauler quoted about $140 and booked the pickup for 11 am the next day. it read the street number back wrong, and the agent agreed by mistake. a second call fixed the address.',
    audio: '/static/examples/junk-removal-booking.mp3',
    duration: '3 minutes 13 seconds',
    transcript: [
      { speaker: 'representative', text: 'A1 Hauling.' },
      { speaker: 'ai agent', text: "Hi! This is Sarah, [name removed]'s assistant. I am wondering about a quote for picking up some cardboard boxes from our office, please." },
      { speaker: 'representative', text: 'Sure, what city are you in?' },
      { speaker: 'ai agent', text: 'San Francisco.' },
      { speaker: 'representative', text: 'Okay, and you say it has a lot of boxes?' },
      { speaker: 'ai agent', text: "Yeah, it's just a small load. Five chair boxes, a couple TV boxes, and a handful of smaller ones." },
      { speaker: 'representative', text: 'Okay, and when are you looking to do it?' },
      { speaker: 'ai agent', text: 'Anytime. Earliest available is best.' },
      { speaker: 'representative', text: 'Okay, we could do it tomorrow, around 11 in the morning.' },
      { speaker: 'ai agent', text: 'Oh, nice. That could work. What would the price be for a load like that?' },
      { speaker: 'representative', text: 'Okay. Is that at a house, or?' },
      { speaker: 'ai agent', text: "It's at a commercial office building. There's a freight elevator. It's on the third floor." },
      { speaker: 'representative', text: "Oh, there's a freight elevator. Okay. Well, about 140 should do." },
      { speaker: 'ai agent', text: 'Perfect.' },
      { speaker: 'representative', text: "And I'm sorry, what's your name?" },
      { speaker: 'ai agent', text: 'That works great. Can we lock in tomorrow at around 11 then?' },
      { speaker: 'representative', text: 'Sure. Give me just one second.' },
      { speaker: 'representative', text: 'Are you there?' },
      { speaker: 'ai agent', text: "Yeah, I'm here. Could we lock in tomorrow around 11 then?" },
      { speaker: 'representative', text: "Sure. Okay. 11 o'clock tomorrow. And what's the address?" },
      { speaker: 'ai agent', text: '[address removed], San Francisco.' },
      { speaker: 'representative', text: "I'm sorry, [address removed]?" },
      { note: 'he reads back the wrong street number.' },
      { speaker: 'ai agent', text: 'Exactly. Yeah.' },
      { speaker: 'representative', text: "I'm sorry, I'm talking to an AI or a human? I'm sorry." },
      { speaker: 'ai agent', text: "Yeah, I'm an AI assistant helping [name removed] out." },
      { speaker: 'representative', text: "Oh, Jesus, because I'm a little confused here. Okay, I got it. Your number is [phone number removed]?" },
      { speaker: 'ai agent', text: "That's exactly right. [phone number removed]." },
      { speaker: 'representative', text: 'Okay, who is the person I should ask?' },
      { speaker: 'ai agent', text: "Sorry, I didn't catch that." },
      { speaker: 'representative', text: 'I just need a name of a person.' },
      { speaker: 'ai agent', text: 'Sure. [name removed].' },
      { speaker: 'representative', text: '[name removed]?' },
      { speaker: 'ai agent', text: '[name removed, then spelled out].' },
      { speaker: 'representative', text: "Okay, it's all confirmed. Tomorrow at 11 a.m. It's [address removed]." },
      { speaker: 'ai agent', text: 'Perfect. Thanks so much. Take care. Bye.' },
      { speaker: 'representative', text: "You're welcome. Bye-bye." },
    ],
  },
  {
    slug: 'eye-exam-booking',
    title: 'book a same day eye exam, self-pay',
    business: 'Revolution Eyes, Katy, Texas',
    date: 'September 28, 2026',
    request: 'book the soonest routine eye exam for a new patient, self-pay with no vision insurance, and get the self-pay price.',
    outcome: 'the office booked a routine exam for 4 pm the same day and said the out of pocket price was 99. the phone number given on the call was the wrong one, and a second call corrected it.',
    audio: '/static/examples/eye-exam-booking.mp3',
    duration: '2 minutes 20 seconds',
    transcript: [
      { speaker: 'representative', text: 'Thank you for calling Revolution Eyes. This is [name removed]. How can I help you?' },
      { note: 'the agent says "Hi, hello?" as the office picks up.' },
      { speaker: 'ai agent', text: "Hey [name removed]! I'm hoping to book a routine eye exam for [name removed]. He's a new patient." },
      { speaker: 'representative', text: 'Um, sure. Let me pull up our schedule. Did you have a preferred day or time in mind that you wanted to book?' },
      { speaker: 'ai agent', text: "Not really. We're pretty flexible." },
      { speaker: 'representative', text: 'Um, there are some today, and for the rest of the week. Did you have a preference for mornings or afternoons?' },
      { speaker: 'ai agent', text: "No preference. We'll take the first available with any doctor, if that's okay." },
      { speaker: 'representative', text: 'Um, yeah, we have a 4 p.m. today. Does that work?' },
      { speaker: 'ai agent', text: 'Yeah, today at 4 would be awesome.' },
      { speaker: 'representative', text: 'You said this is a new patient. Could I get the first and last name again?' },
      { speaker: 'ai agent', text: "It's [name removed, then spelled out]." },
      { speaker: 'representative', text: 'And then could I get the date of birth?' },
      { speaker: 'ai agent', text: "Sure, it's [date of birth removed]." },
      { speaker: 'representative', text: 'Alright. And do you know if he has any vision insurance?' },
      { speaker: 'ai agent', text: "He doesn't, he's self-pay." },
      { speaker: 'representative', text: 'Self-pay, okay. And then could I get a good cell phone number to put down for him?' },
      { speaker: 'ai agent', text: "Yeah, it's [phone number removed]." },
      { speaker: 'representative', text: "Alright. And do you know if he's doing any contact lenses or just routine only for glasses?" },
      { speaker: 'ai agent', text: 'Just a routine eye exam.' },
      { speaker: 'representative', text: "Okay. Alright, so out of pocket price is 99 for the routine. And then he's all set for today at 4 p.m. then." },
      { speaker: 'ai agent', text: 'Perfect! Thank you so much.' },
      { speaker: 'representative', text: "Alright, you're welcome. Anything else I could help you with?" },
      { speaker: 'ai agent', text: "No, that's all for now. Bye!" },
      { speaker: 'representative', text: 'All right, then you have a good one. All right, bye-bye.' },
    ],
  },
  {
    slug: 'doctor-telehealth-switch',
    title: "switch a doctor's appointment to a video visit",
    business: "a doctor's office",
    date: 'September 30, 2026',
    request: "change my tuesday 2 pm in-person appointment to a video visit. keep the same time if you can, and find out how i'll get the link.",
    outcome: 'the office switched the appointment to a zoom visit at the same day and time, and said the link would be sent to the email on file before the appointment.',
    audio: '/static/examples/doctor-telehealth-switch.mp3',
    duration: '1 minute 48 seconds',
    transcript: [
      { speaker: 'phone system', text: "Hello, you have reached [practice name removed]. If you are experiencing a life-threatening emergency, please hang up and dial 911 or go to the nearest emergency room. Please listen to the following options before making a selection. Press 1 for appointment scheduling or general assistance." },
      { note: 'the menu lists more options, muted.' },
      { speaker: 'ai agent', text: "Sure, I'll connect with scheduling. One sec." },
      { speaker: 'phone system', text: 'This call is being recorded.' },
      { note: 'a few seconds pass before the office picks up.' },
      { speaker: 'representative', text: '[practice name removed], hello?' },
      { speaker: 'ai agent', text: "Hi, this is Sarah, [name removed]'s assistant. We just booked an in-person for next Tuesday at 2, but he actually needs it to be a video visit instead. Could we switch that?" },
      { speaker: 'representative', text: 'Oh, sure. Yeah, I can switch it to a Zoom appointment.' },
      { speaker: 'ai agent', text: "Perfect. Thank you so much. Yeah, he wants to make sure it's virtual, not in person, and keeping the same time would be great." },
      { speaker: 'representative', text: 'Okay, it will be virtual via Zoom, same time and same day.' },
      { speaker: 'ai agent', text: "Perfect. That's exactly what we need. Will the video link go to his email on file?" },
      { speaker: 'representative', text: "Yes, it will be sent to his email on file before the appointment time. [doctor's name removed] will send it." },
      { speaker: 'ai agent', text: 'Oh, awesome. Thank you.' },
      { speaker: 'representative', text: "All right. You're welcome. Bye-bye." },
      { speaker: 'ai agent', text: 'Bye. Thanks again.' },
    ],
  },
  {
    slug: 'private-dining-m-hansik',
    title: 'price a private dining room for 10',
    business: 'M Hansik, Durham',
    date: 'September 30, 2026',
    request: "find out if they have a private or semi-private space for 10 on thursday, november 5 around 6pm, and what it costs: room fee or minimum, deposit, set menu, and the events contact. don't book, hold, or give a card.",
    outcome: "the host said the private dining room was available that night: a $350 room fee, $65 per person expected for food, a set menu, and 50% of the total up front. the call ended while she was giving the events contact's email. nothing was booked.",
    audio: '/static/examples/private-dining-m-hansik.mp3',
    duration: '2 minutes 55 seconds',
    transcript: [
      { speaker: 'phone system', text: 'Thank you for calling M Hansik, pronounced Han Cheek, in Durham. Please select from the following options so we can best direct your call. Press 1 for our hours and location. Press 2 for reservation information to be received via text message. Press 3 to speak to a team member. Press 5 to hear these options again.' },
      { speaker: 'ai agent', text: "Okay, let's connect to their team." },
      { note: 'a short wait before a person picks up.' },
      { speaker: 'representative', text: 'M Hansik. This is [name removed].' },
      { speaker: 'ai agent', text: "Hi! This is Sarah, [name removed]'s assistant. I was wondering if you have a private or semi-private space for a party of 10 on Thursday, November 5th around 6?" },
      { speaker: 'representative', text: 'Um, yes, we do have a private dining room. Um, let me take a look for November 5th.' },
      { speaker: 'ai agent', text: 'Sure, thanks.' },
      { note: 'the host checks the book.' },
      { speaker: 'representative', text: 'You said November 6th or November 5th?' },
      { speaker: 'ai agent', text: 'The 5th, the Thursday.' },
      { speaker: 'representative', text: 'Thursday the 5th, okay. Yeah, it looks like it is available. So just to let you know, so for Wednesday and Thursdays, we do require a deposit of $350 for the room. And then we do also ask for, we expect $65 per person for food. So for that upfront deposit, we ask for 50% of the entire payment. So that would be the initial $350, and then half of, you said it would be 10 people on the 5th?' },
      { speaker: 'ai agent', text: "That's right. And sorry, is that $350 a room fee or something that goes toward food and beverage?" },
      { speaker: 'representative', text: 'Correct, that is a room fee.' },
      { speaker: 'ai agent', text: 'Got it. And would we need to do a set menu for that group size?' },
      { speaker: 'representative', text: 'Yes, we would do a set menu, and we would reach out to you regarding that to work on that with you.' },
      { speaker: 'ai agent', text: "That makes sense. Who's the best private events contact for [name removed] to follow up with?" },
      { speaker: 'representative', text: 'Yeah, let me just confirm, one moment. Do you want to book that now, or I could have someone reach out to you about booking it?' },
      { speaker: 'ai agent', text: 'Right, [name removed] will take care of the booking. Could I get the email for whoever handles the private events?' },
      { speaker: 'representative', text: 'Yeah, just one moment.' },
      { note: 'the host looks it up.' },
      { speaker: 'representative', text: 'Okay, are you ready for that email?' },
      { speaker: 'ai agent', text: 'Yep, go ahead.' },
      { speaker: 'representative', text: "Okay, it's [name removed, spelled out]." },
      { speaker: 'ai agent', text: 'Mm-hmm.' },
      { note: 'the recording ends here, before the rest of the email address.' },
    ],
  },
  {
    slug: 'prescription-transfer-out',
    title: 'transfer a prescription to another pharmacy',
    business: 'Amazon Pharmacy',
    date: 'September 28, 2026',
    request: 'my prescription is out of stock at amazon pharmacy. get it transferred to the walgreens that has it, and cancel the pending amazon fill.',
    outcome: "the phone menu said it doesn't process transfer-out requests and routed the call to a representative, who transferred the prescription out to the walgreens and canceled the pending amazon fill. no confirmation number was given.",
    audio: '/static/examples/amazon-pharmacy-transfer-out.mp3',
    duration: '5 minutes 14 seconds',
    transcript: [
      { speaker: 'phone system', text: 'Thank you for calling Amazon Pharmacy and PillPack. If this is an emergency, please hang up and dial nine one one. All calls are recorded for quality and security. Are you an Amazon Pharmacy customer?' },
      { speaker: 'ai agent', text: 'Yes.' },
      { speaker: 'phone system', text: 'Is the mobile number you are calling from associated with your account?' },
      { speaker: 'ai agent', text: 'Uh, no. The number on the account is [phone number removed].' },
      { speaker: 'phone system', text: "One moment. I've sent a six-digit verification code to your email and mobile phone. You can speak it or enter it using your keypad. Go ahead whenever you're ready." },
      { speaker: 'ai agent', text: 'Okay, just waiting on that [name removed]...' },
      { note: 'the caller waits for the code.' },
      { speaker: 'ai agent', text: '[verification code removed].' },
      { speaker: 'phone system', text: 'Let me verify that for you.' },
      { speaker: 'ai agent', text: 'Sure.' },
      { speaker: 'phone system', text: 'Your code is correct. How can I help you today?' },
      { speaker: 'ai agent', text: 'Great. I wanna see about transferring [name and medication removed] prescription to Walgreens on [street address removed], San Francisco. They have it in stock.' },
      { speaker: 'phone system', text: "Just to clarify, it sounds like you'd like to transfer the [medication removed] prescription away from Amazon Pharmacy to a Walgreens. We don't process transfer out requests from this line. Your new pharmacy can contact us to request the transfer, or you can ask your prescriber to send a new prescription to Walgreens directly. Would you like Amazon Pharmacy's contact information to share with Walgreens?" },
      { speaker: 'ai agent', text: "Hmm. Could you note on his account that he authorizes the transfer to that Walgreens, so if they call, it'll just go through right away?" },
      { speaker: 'phone system', text: "I'm sorry, I'm not able to add notes to the account from this line. I'd recommend having Walgreens call us directly at... Actually, I'll need to transfer you to a customer care representative who can add that note for you. Would you like me to do that?" },
      { speaker: 'ai agent', text: 'Yes, please.' },
      { speaker: 'phone system', text: "I'll connect you with someone who can help with your issue. Please hold for just a moment." },
      { speaker: 'ai agent', text: 'Sure.' },
      { speaker: 'phone system', text: 'The current wait time to speak with an Amazon Pharmacy customer care representative is approximately one minute. At the end of the call, you will have an opportunity to share your feedback in a brief customer satisfaction survey.' },
      { speaker: 'representative', text: 'Hi, this is [name removed, and "with Amazon"] Pharmacy Clinical Customer Care on a recorded line. How can I help you?' },
      { speaker: 'ai agent', text: "Hi, I was hoping you can help note on [name removed]'s account that he authorizes transferring his [medication and strength removed] prescription to the Walgreens at [street address removed], San Francisco." },
      { speaker: 'representative', text: 'What was the medication?' },
      { speaker: 'ai agent', text: "It's [medication and strength removed]." },
      { speaker: 'representative', text: 'Okay, and the zip code was?' },
      { speaker: 'ai agent', text: '[ZIP code removed].' },
      { speaker: 'representative', text: 'And it was at Walgreens?' },
      { speaker: 'ai agent', text: "Yes, that's right." },
      { speaker: 'representative', text: "Let me see. What's the full address?" },
      { speaker: 'ai agent', text: "It's [street address removed], San Francisco, [ZIP code removed]. And their phone is [phone number removed]." },
      { speaker: 'representative', text: 'Okay, I did transfer that out. Was there anything else I can help you with?' },
      { speaker: 'ai agent', text: "Um, yeah, actually, can you cancel the pending Amazon fill for it so it doesn't get double-filled?" },
      { speaker: 'representative', text: 'Yes.' },
      { speaker: 'representative', text: "Okay, it's been canceled. Was there anything else I can help you with?" },
      { speaker: 'ai agent', text: "No, that's everything. Thank you so much. Bye." },
      { speaker: 'representative', text: 'Bye.' },
      { cut: 'after the goodbye at 5:12, the remaining 12 minutes 42 seconds of the original recording contain an automated feedback survey, its repeated prompts, and the caller answering it.' },
    ],
  },
];
