/**
 * Editorial subjects define eligible related articles; embeddings rank within them.
 * Classify the reader's actual subject or task, not incidental wording such as
 * prices, phone numbers, customer service, or the fact that an AI placed the call.
 * Multiple subjects are appropriate when an article substantially covers both.
 * General scheduling guides can span subjects; a domain-specific appointment
 * stays in that domain so shared booking vocabulary cannot connect unrelated needs.
 * Add subjects for every new article without selecting individual related links.
 */
export const RELATED_TOPICS: Record<string, string[]> = {
  'customer-story-flight-credit': ['airlines'],
  'customer-story-rick-dinner-reservation': ['dining'],
  'customer-story-dental-appointments': ['healthcare'],
  'customer-story-joe-dress-shoes': ['retail-shopping'],
  'aaa-insurance-customer-service': ['insurance'],
  'adderall-shortage': ['pharmacy'],
  'agent-web-research-phone-calls-sf-private-dining': ['agent-software', 'dining'],
  'ai-agent-that-makes-phone-calls': ['agent-software'],
  'ai-personal-assistant-appointment-booking': ['appointment-management', 'healthcare', 'dining'],
  'ai-phone-tree-navigation': ['agent-software', 'voice-technology'],
  'allstate-customer-service-number': ['insurance'],
  'amazon-pharmacy-phone-number': ['pharmacy'],
  'american-airlines-flight-credit': ['airlines'],
  'aquasana-return-exception': ['retail-shopping'],
  'bland-ai-alternatives': ['agent-software'],
  'book-dinner-reservation-by-phone': ['dining'],
  'book-haircut-appointment': ['hair-care'],
  'cancel-audible': ['subscription-cancellation', 'media-subscriptions'],
  'cancel-crunch': ['subscription-cancellation', 'fitness'],
  'cancel-factor': ['subscription-cancellation', 'meal-delivery'],
  'cancel-fubo': ['subscription-cancellation', 'media-subscriptions'],
  'cancel-hellofresh': ['subscription-cancellation', 'meal-delivery'],
  'cancel-la-fitness': ['subscription-cancellation', 'fitness'],
  'cancel-planet-fitness': ['subscription-cancellation', 'fitness'],
  'cascaded-voice-stack-vs-gpt-live': ['agent-software', 'voice-technology'],
  'claude-code-phone-calls': ['agent-software'],
  'codex-phone-calls': ['agent-software'],
  'costco-eye-exam-cost': ['healthcare'],
  'costco-tire-appointment-cancel-refund': ['car-maintenance'],
  'couch-reupholstery-cost': ['furniture-home-services'],
  'delta-customer-service': ['airlines'],
  'directv-customer-service': ['telecom', 'subscription-cancellation'],
  'dog-teeth-cleaning-cost': ['veterinary'],
  'doordash-customer-service-number': ['meal-delivery'],
  'drop-off-vet-appointment': ['veterinary'],
  'etihad-customer-service': ['airlines'],
  'everything-we-have-improved-since-launch': ['agent-software', 'voice-technology'],
  'experian-phone-number': ['personal-finance'],
  'eye-exam-cost-without-insurance': ['healthcare'],
  'fabletics-customer-service': ['subscription-cancellation', 'retail-shopping'],
  'fedex-customer-service-number': ['shipping'],
  'fifth-third-bank-customer-service': ['personal-finance'],
  'follow-up-appointment-telehealth': ['healthcare'],
  'fpl-phone-number': ['utilities'],
  'furniture-refinishing-cost': ['furniture-home-services'],
  'geico-customer-service': ['insurance'],
  'grok-bot-reusable-skills': ['agent-software'],
  'grok-bot-template-troubleshooting': ['agent-software'],
  'grok-bot-templates': ['agent-software'],
  'grok-bot-vs-meta-muse': ['agent-software'],
  'grok-connectors-mcp-phone-calls': ['agent-software'],
  'gym-day-pass': ['fitness'],
  'gyms-with-sauna-near-me': ['fitness'],
  'hertz-customer-service-number': ['car-rental'],
  'how-long-to-reach-a-human': ['airlines', 'insurance', 'personal-finance', 'subscription-cancellation', 'telecom'],
  'how-much-does-blood-work-cost': ['healthcare'],
  'how-to-cancel-siriusxm': ['subscription-cancellation', 'media-subscriptions'],
  'how-to-find-a-new-primary-care-doctor': ['healthcare', 'insurance'],
  'how-to-transfer-a-prescription': ['pharmacy'],
  'hulu-customer-service-number': ['subscription-cancellation', 'media-subscriptions'],
  'instinct-ai-phone-calls': ['agent-software'],
  'junk-removal-cost': ['furniture-home-services'],
  'lawyer-consultation-fee': ['legal-business-paperwork'],
  'les-schwab-oil-change': ['car-maintenance'],
  'macys-bow-tie-stock-check': ['retail-shopping'],
  'mandarin-phone-call-scheduling': ['appointment-management'],
  'meta-muse-ai-agent-phone-calls': ['agent-software'],
  'meta-muse-first-task': ['agent-software'],
  'meta-muse-supplier-quotes': ['agent-software', 'business-procurement'],
  'muse-code-mcp-phone-calls': ['agent-software'],
  'need-dress-shoes-today': ['retail-shopping'],
  'ohio-workers-compensation-insurance': ['insurance', 'legal-business-paperwork'],
  'openai-realtime-voices-phone-calls': ['voice-technology', 'agent-software'],
  'paypal-customer-service-number': ['personal-finance'],
  'phone-calling-mcp-comparison': ['agent-software'],
  'pottery-barn-customer-service': ['retail-shopping', 'furniture-home-services'],
  'priceline-customer-service': ['airlines', 'car-rental'],
  'private-dining-room-cost': ['dining'],
  'reschedule-dentist-appointment': ['healthcare'],
  'reschedule-doctor-appointment': ['healthcare'],
  'running-late-to-appointment': ['healthcare'],
  'running-late-to-barber': ['hair-care'],
  'schedule-phone-calls-claude-code-codex': ['agent-software'],
  'spectrum-retention-department': ['telecom', 'subscription-cancellation'],
  't3-code-phone-calls': ['agent-software'],
  'twilio-mcp-phone-calls': ['agent-software'],
  'united-change-flight': ['airlines'],
  'unitedhealthcare-phone-number': ['healthcare', 'insurance'],
  'ups-contact-number': ['shipping'],
  'usaa-phone-number': ['insurance', 'personal-finance'],
  'vapi-alternatives': ['agent-software'],
  'vercel-ai-sdk-phone-calls': ['agent-software'],
  'verizon-customer-service': ['telecom'],
  'veterinary-behavior-consultation-call': ['veterinary'],
  'walmart-oil-change-prices': ['car-maintenance'],
  'wayfair-customer-service': ['retail-shopping', 'furniture-home-services'],
  'wheel-alignment-cost': ['car-maintenance'],
  'windstream-customer-service': ['telecom'],
  'wyoming-registered-agent-consent-form': ['legal-business-paperwork'],
};
